/**
 * @generated
 * @file Padding (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./modules/Basic/components/Block";

/**
 * Props for {@link Padding}
 */
export type PaddingProps = {
  space?: "Small (3rem)" | "Medium (6rem)" | "Large (9rem)" | "None";
};

/**
 * Padding
 *
 */
export function Padding({ space = "Small (3rem)" }: PaddingProps) {
  const _styleVariantMap = {
    "Small (3rem)": "",
    "Medium (6rem)": "w-variant-4e707de5-bf1e-dd42-7fb6-ac24ce686a4c",
    "Large (9rem)": "w-variant-83eec681-a82d-6e26-f749-52e4ca458c13",
    None: "w-variant-c5e33d14-e297-6cd7-2fd0-a5ca94b32941",
  };

  const _activeStyleVariant = _styleVariantMap[space];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`spacer-component ${_activeStyleVariant}`}
        tag={"div"}
      />
    </div>
  );
}
