export type FieldType = "text" | "textarea" | "richtext" | "date" | "boolean" | "select" | "readonly" | "image";

export type FieldDef = {
  name: string;
  label: string;
  type: FieldType;
  locale?: boolean; // if true, field has _en/_fr variants
  options?: { value: string; label: string }[]; // for select
  required?: boolean;
};

export type TableConfig = {
  slug: string; // URL slug: "blog-posts"
  table: string; // DB table: "blog_posts"
  displayName: string;
  listColumns: { key: string; label: string }[];
  orderBy: { column: string; ascending: boolean };
  fields: FieldDef[];
};

export const TABLES: TableConfig[] = [
  {
    slug: "blog-posts",
    table: "blog_posts",
    displayName: "Blog Posts",
    listColumns: [
      { key: "name_en", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "date_de_publication", label: "Date" },
      { key: "published", label: "Status" },
    ],
    orderBy: { column: "date_de_publication", ascending: false },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "slug_fr", label: "Slug (FR)", type: "text" },
      { name: "name", label: "Title", type: "text", locale: true, required: true },
      { name: "description", label: "Description", type: "textarea", locale: true },
      { name: "body", label: "Body", type: "richtext", locale: true },
      { name: "banner_url", label: "Banner", type: "image" },
      { name: "banner_alt_desc", label: "Banner Alt", type: "text" },
      { name: "date_de_publication", label: "Publication Date", type: "date" },
      { name: "seo_title", label: "SEO Title", type: "text", locale: true },
      { name: "seo_meta_desc", label: "Meta Description", type: "textarea", locale: true },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
      { name: "en_avant", label: "Featured", type: "boolean" },
    ],
  },
  {
    slug: "news",
    table: "news",
    displayName: "News",
    listColumns: [
      { key: "name_en", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "published_date", label: "Date" },
      { key: "published", label: "Status" },
    ],
    orderBy: { column: "published_date", ascending: false },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "slug_fr", label: "Slug (FR)", type: "text" },
      { name: "name", label: "Title", type: "text", locale: true, required: true },
      { name: "description", label: "Description", type: "textarea", locale: true },
      { name: "body", label: "Body", type: "richtext", locale: true },
      { name: "banner_url", label: "Banner", type: "image" },
      { name: "banner_alt_desc", label: "Banner Alt", type: "text" },
      { name: "published_date", label: "Published Date", type: "date" },
      { name: "seo_title", label: "SEO Title", type: "text", locale: true },
      { name: "seo_meta_desc", label: "Meta Description", type: "textarea", locale: true },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
      { name: "en_avant", label: "Featured", type: "boolean" },
    ],
  },
  {
    slug: "guides",
    table: "guides",
    displayName: "Guides",
    listColumns: [
      { key: "name_en", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "date", label: "Date" },
      { key: "published", label: "Status" },
    ],
    orderBy: { column: "date", ascending: false },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "slug_fr", label: "Slug (FR)", type: "text" },
      { name: "name", label: "Title", type: "text", locale: true, required: true },
      { name: "description", label: "Description", type: "textarea", locale: true },
      { name: "body", label: "Body", type: "richtext", locale: true },
      { name: "form", label: "Form HTML", type: "richtext", locale: true },
      { name: "banner_url", label: "Banner", type: "image" },
      { name: "banner_alt_desc", label: "Banner Alt", type: "text" },
      { name: "document_url", label: "Document URL", type: "text" },
      { name: "date", label: "Date", type: "date" },
      { name: "seo_title", label: "SEO Title", type: "text", locale: true },
      { name: "seo_meta_desc", label: "Meta Description", type: "textarea", locale: true },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
    ],
  },
  {
    slug: "customer-stories",
    table: "customer_stories",
    displayName: "Customer Stories",
    listColumns: [
      { key: "name_en", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "publish_date", label: "Date" },
      { key: "published", label: "Status" },
    ],
    orderBy: { column: "publish_date", ascending: false },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "slug_fr", label: "Slug (FR)", type: "text" },
      { name: "name", label: "Title", type: "text", locale: true, required: true },
      { name: "description", label: "Description", type: "textarea", locale: true },
      { name: "about", label: "About", type: "textarea", locale: true },
      { name: "entreprise", label: "Company Name", type: "text" },
      { name: "localisation", label: "Location", type: "text" },
      { name: "team_size", label: "Team Size", type: "text" },
      { name: "score", label: "Revenue/Score", type: "text" },
      { name: "banner_url", label: "Banner", type: "image" },
      { name: "business_logo_url", label: "Business Logo", type: "image" },
      { name: "publish_date", label: "Publish Date", type: "date" },
      { name: "presentation", label: "Presentation", type: "richtext", locale: true },
      { name: "challenges", label: "Challenges", type: "richtext", locale: true },
      { name: "contexte_rse", label: "CSR Context", type: "richtext", locale: true },
      { name: "solution", label: "Solution", type: "richtext", locale: true },
      { name: "impact", label: "Impact", type: "richtext", locale: true },
      { name: "ending", label: "Ending", type: "richtext", locale: true },
      { name: "challenge_summary", label: "Challenge Summary", type: "richtext", locale: true },
      { name: "impact_summary", label: "Impact Summary", type: "richtext", locale: true },
      { name: "medaille", label: "Medal", type: "text", locale: true },
      { name: "quote", label: "Quote 1", type: "textarea", locale: true },
      { name: "quote_2", label: "Quote 2", type: "textarea", locale: true },
      { name: "quote_3", label: "Quote 3", type: "textarea", locale: true },
      { name: "quote_author", label: "Quote Author", type: "text" },
      { name: "quote_author_role", label: "Quote Author Role", type: "text" },
      { name: "quote_author_picture_url", label: "Quote Author Picture", type: "image" },
      { name: "seo_title", label: "SEO Title", type: "text", locale: true },
      { name: "seo_meta_desc", label: "Meta Description", type: "textarea", locale: true },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
      { name: "featured", label: "Featured", type: "boolean" },
      { name: "display_on_showcase", label: "Display on Showcase", type: "boolean" },
    ],
  },
  {
    slug: "collection-items",
    table: "collection_items",
    displayName: "Collection Items",
    listColumns: [
      { key: "name_en", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "date_de_publication", label: "Date" },
      { key: "published", label: "Status" },
    ],
    orderBy: { column: "ordre", ascending: true },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "slug_fr", label: "Slug (FR)", type: "text" },
      { name: "name", label: "Title", type: "text", locale: true, required: true },
      { name: "description", label: "Description", type: "textarea", locale: true },
      { name: "body", label: "Body", type: "richtext", locale: true },
      { name: "banner_url", label: "Banner", type: "image" },
      { name: "banner_alt_desc", label: "Banner Alt", type: "text" },
      { name: "categorie", label: "Category", type: "text" },
      { name: "ordre", label: "Sort Order", type: "text" },
      { name: "date_de_publication", label: "Publication Date", type: "date" },
      { name: "seo_title", label: "SEO Title", type: "text", locale: true },
      { name: "seo_meta_desc", label: "Meta Description", type: "textarea", locale: true },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
    ],
  },
  {
    slug: "authors",
    table: "authors",
    displayName: "Authors",
    listColumns: [
      { key: "name", label: "Name" },
      { key: "slug", label: "Slug" },
      { key: "job_title", label: "Job Title" },
    ],
    orderBy: { column: "name", ascending: true },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "job_title", label: "Job Title", type: "text" },
      { name: "job_title_fr", label: "Job Title (FR)", type: "text" },
      { name: "picture_url", label: "Picture", type: "image" },
      { name: "linkedin_url", label: "LinkedIn URL", type: "text" },
      { name: "description_en", label: "Description (EN)", type: "richtext" },
      { name: "description_fr", label: "Description (FR)", type: "richtext" },
    ],
  },
  {
    slug: "testimonials",
    table: "testimonials",
    displayName: "Testimonials",
    listColumns: [
      { key: "name", label: "Company" },
      { key: "customer_name", label: "Person" },
      { key: "sort_order", label: "Order" },
    ],
    orderBy: { column: "sort_order", ascending: true },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name", label: "Company Name", type: "text", required: true },
      { name: "customer_name", label: "Person Name", type: "text" },
      { name: "job_title", label: "Job Title", type: "text" },
      { name: "job_title_fr", label: "Job Title (FR)", type: "text" },
      { name: "quote_en", label: "Quote (EN)", type: "textarea" },
      { name: "quote_fr", label: "Quote (FR)", type: "textarea" },
      { name: "logo_url", label: "Company Logo", type: "image" },
      { name: "profile_picture_url", label: "Profile Picture", type: "image" },
      { name: "sort_order", label: "Sort Order", type: "text" },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
    ],
  },
  {
    slug: "frameworks",
    table: "frameworks",
    displayName: "Frameworks",
    listColumns: [
      { key: "name", label: "Name" },
      { key: "slug", label: "Slug" },
      { key: "sort_order", label: "Order" },
    ],
    orderBy: { column: "sort_order", ascending: true },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "frameworks_type", label: "Type", type: "text" },
      { name: "is_filter", label: "Is Filter", type: "boolean" },
      { name: "collection_url", label: "Collection URL", type: "text" },
      { name: "page_url", label: "Page URL", type: "text" },
      { name: "sort_order", label: "Sort Order", type: "text" },
    ],
  },
  {
    slug: "industries",
    table: "industries",
    displayName: "Industries",
    listColumns: [
      { key: "name_en", label: "Name (EN)" },
      { key: "name_fr", label: "Name (FR)" },
      { key: "slug", label: "Slug" },
    ],
    orderBy: { column: "name_en", ascending: true },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "name_en", label: "Name (EN)", type: "text", required: true },
      { name: "name_fr", label: "Name (FR)", type: "text" },
    ],
  },
  {
    slug: "company-logos",
    table: "company_logos",
    displayName: "Company Logos",
    listColumns: [
      { key: "name", label: "Name" },
      { key: "sort_order", label: "Order" },
      { key: "published", label: "Status" },
    ],
    orderBy: { column: "sort_order", ascending: true },
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "logo_url", label: "Logo", type: "image", required: true },
      { name: "case_study_url", label: "Case Study URL", type: "text" },
      { name: "sort_order", label: "Sort Order", type: "text" },
      { name: "published", label: "Published", type: "boolean" },
    ],
  },
  {
    slug: "events",
    table: "events",
    displayName: "Events",
    listColumns: [
      { key: "name_en", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "date", label: "Date" },
    ],
    orderBy: { column: "date", ascending: false },
    fields: [
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "slug_fr", label: "Slug (FR)", type: "text" },
      { name: "name", label: "Title", type: "text", locale: true, required: true },
      { name: "description", label: "Description", type: "textarea", locale: true },
      { name: "body", label: "Body", type: "richtext", locale: true },
      { name: "form", label: "Form HTML", type: "richtext", locale: true },
      { name: "link_to_livestorm_event", label: "Livestorm Link", type: "text" },
      { name: "banner_url", label: "Banner", type: "image" },
      { name: "banner_alt_desc", label: "Banner Alt", type: "text" },
      { name: "document_url", label: "Document URL", type: "text" },
      { name: "date", label: "Date", type: "date" },
      { name: "seo_title", label: "SEO Title", type: "text", locale: true },
      { name: "seo_meta_desc", label: "Meta Description", type: "textarea", locale: true },
      { name: "published", label: "Published", type: "boolean" },
      { name: "archived", label: "Archived", type: "boolean" },
    ],
  },
];

export function getTableConfig(slug: string): TableConfig | undefined {
  return TABLES.find((t) => t.slug === slug);
}
