/**
 * @generated
 * @file AiAgentCard (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";
import Image from "../modules/Basic/components/Image";
import Paragraph from "../modules/Basic/components/Paragraph";

/**
 * Props for {@link AiAgentCard}
 */
export type AiAgentCardProps = {};

/**
 * AiAgentCard
 *
 */
export function AiAgentCard({}: AiAgentCardProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        agents-form={"agent-1"}
        className={"agents_card"}
        id={"w-node-_7378fd3d-5d16-0008-952d-e7003c27187f-3c27187f"}
        tag={"div"}
      >
        <Block className={"agents_card_icon"} tag={"div"}>
          <Image
            alt={""}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c152c34ca7caf3a490b8_Icon%201.png"
            }
            width={"auto"}
          />
        </Block>
        <Block className={"spacer-1rem"} tag={"div"} />
        <Block className={"agents_card_header"} tag={"div"}>
          <Heading className={"heading-size-1x375rem"} tag={"h3"}>
            {"AIAGENT1"}
          </Heading>
          <Paragraph className={"tag is--orange"}>{"Coming soon"}</Paragraph>
        </Block>
        <Block className={"spacer-0x5rem"} tag={"div"} />
        <Paragraph className={"text-size-1rem text-color-neutral"}>
          {
            "Automate your corporate social responsibility reporting and compliance tracking"
          }
        </Paragraph>
        <Block className={"spacer-auto"} tag={"div"} />
        <Block className={"spacer-2rem"} tag={"div"} />
        <Block agents-form-element={"button"} className={"button"} tag={"div"}>
          <Paragraph>{"Join Waitlist"}</Paragraph>
        </Block>
        <HtmlEmbed
          agents-form-element={"form-wrapper"}
          className={"hide"}
          content={
            '<script>\n  hbspt.forms.create({\n    portalId: "26313404",\n    formId: "7468ad63-da3f-4532-acf3-16408c4d8cce",\n    region: "eu1"\n  });\n</script>'
          }
        />
      </Block>
    </div>
  );
}
