/**
 * @generated
 * @file CardIcon (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Image from "../modules/Basic/components/Image";
import Paragraph from "../modules/Basic/components/Paragraph";

/**
 * Props for {@link CardIcon}
 */
export type CardIconProps = {
  description?: React.ReactNode;
  icon?: string;
  title?: React.ReactNode;
  variant?: "Primary" | "Secondary" | "Secondary + Blend logo";
};

/**
 * CardIcon
 *
 */
export function CardIcon({
  description = "Description",
  icon = "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682d7fad3c89203197a56fb7_image.svg",
  title = "Heading",
  variant = "Primary",
}: CardIconProps) {
  const _styleVariantMap = {
    Primary: "",
    Secondary: "w-variant-ba013e42-81a1-5445-06dc-1cad1363eec7",
    "Secondary + Blend logo": "w-variant-09d5c0ae-36c1-e974-3edd-0ee349a57bda",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`card-icon ${_activeStyleVariant}`}
        id={"w-node-e1e255de-dfb2-a541-0c0a-b4c560421b5e-60421b5e"}
        tag={"div"}
      >
        <Image
          alt={""}
          className={`card-icon_image ${_activeStyleVariant}`}
          height={"auto"}
          loading={"lazy"}
          src={icon}
          width={"auto"}
        />
        <Block
          className={`spacer-3rem spacer-mob-2rem ${_activeStyleVariant}`}
          tag={"div"}
        />
        <Heading
          className={`heading-size-2rem ${_activeStyleVariant}`}
          tag={"h3"}
        >
          {title}
        </Heading>
        <Block
          className={`spacer-0x75rem ${_activeStyleVariant}`}
          tag={"div"}
        />
        <Paragraph className={`text-size-1x375rem ${_activeStyleVariant}`}>
          {description}
        </Paragraph>
        <Block className={`spacer-auto ${_activeStyleVariant}`} tag={"div"} />
      </Block>
    </div>
  );
}
