/**
 * @generated
 * @file CardTestimonial (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Image from "../modules/Basic/components/Image";
import Paragraph from "../modules/Basic/components/Paragraph";

/**
 * Props for {@link CardTestimonial}
 */
export type CardTestimonialProps = {
  authorAuthorImage?: string;
  authorAuthorName?: React.ReactNode;
  authorAuthorRole?: React.ReactNode;
  logo?: string;
  testimonial?: React.ReactNode;
};

/**
 * CardTestimonial
 *
 */
export function CardTestimonial({
  authorAuthorImage = "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682d7fad3c89203197a56fb7_image.svg",
  authorAuthorName = "Lorem ipsum",
  authorAuthorRole = "CEO of lorem ipsum",
  logo = "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682d7fad3c89203197a56fb7_image.svg",
  testimonial = '"Ditto ensures that everything is done efficiently. The quality of the work is evident, which is very reassuring as we move forward on managing our CSR compliance."',
}: CardTestimonialProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"card-testimonial"}
        id={"w-node-_516beb1e-6d9b-dbe9-d689-3b1c31682c03-31682c03"}
        tag={"div"}
      >
        <Image
          alt={""}
          className={"card-testimonial_logo"}
          height={"Auto"}
          loading={"lazy"}
          src={logo}
          width={"Auto"}
        />
        <Block className={"spacer-3rem spacer-mob-2rem"} tag={"div"} />
        <Paragraph className={"heading-size-2rem"}>{testimonial}</Paragraph>
        <Block className={"spacer-1x5rem spacer-mob-1rem"} tag={"div"} />
        <Block className={"spacer-auto"} tag={"div"} />
        <Block className={"profile_wrapper"} tag={"div"}>
          <Block className={"profile_image"} tag={"div"}>
            <Image
              alt={""}
              className={"media-full-size"}
              height={"48"}
              loading={"lazy"}
              src={authorAuthorImage}
              width={"48"}
            />
          </Block>
          <Block className={"profile_content"} tag={"div"}>
            <Heading className={"text-size-1rem text-weight-400"} tag={"h4"}>
              {authorAuthorName}
            </Heading>
            <Block className={"spacer-0x25rem"} tag={"div"} />
            <Paragraph className={"text-size-0x875rem text-color-neutral"}>
              {authorAuthorRole}
            </Paragraph>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
