/**
 * @generated
 * @file CardImage (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Image from "../modules/Basic/components/Image";
import Link from "../modules/Basic/components/Link";
import Paragraph from "../modules/Basic/components/Paragraph";

/**
 * Props for {@link CardImage}
 */
export type CardImageProps = {
  imageThumbnailDesc?: unknown;
  imageThumbnailImage?: string;
  labelLabel?: React.ReactNode;
  labelLabelField?: string;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  location?: React.ReactNode;
  locationVisibility?: boolean;
  textDesc?: React.ReactNode;
  textTitle?: React.ReactNode;
  variant?: "Base" | "First child";
};

/**
 * CardImage
 *
 */
export function CardImage({
  imageThumbnailDesc = "__wf_reserved_inherit",
  imageThumbnailImage = "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d7fad3c89203197a56fb7_image.svg",
  labelLabel = "lorem ipsum",
  labelLabelField = "",

  link = {
    href: "#",
  },

  location = "Lorem ipsum",
  locationVisibility = true,
  textDesc = "Lorem ipsum",
  textTitle = "Lorem ipsum",
  variant = "Base",
}: CardImageProps) {
  const _styleVariantMap = {
    Base: "",
    "First child": "w-variant-94d18820-9735-d9f3-60bc-c13465ec1086",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`card-image ${_activeStyleVariant}`}
        id={"w-node-_360a829d-4cbf-5176-01bb-3cb8a26a988f-a26a988f"}
        tag={"div"}
      >
        <Block
          className={`card-image_thumbnail ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Image
            className={`media-full-size ${_activeStyleVariant}`}
            height={"auto"}
            loading={"lazy"}
            src={imageThumbnailImage}
            width={"auto"}
          />
        </Block>
        <Block
          className={`card-image_content ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Block
            className={`spacer-1x5rem spacer-mob-1rem ${_activeStyleVariant}`}
            tag={"div"}
          />
          <Paragraph
            className={`label ${_activeStyleVariant}`}
            fs-list-field={labelLabelField}
          >
            {labelLabel}
          </Paragraph>
          <Block
            className={`spacer-0x75rem ${_activeStyleVariant}`}
            tag={"div"}
          />
          <Block
            className={`card-image_link_wrapper ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Link
              block={""}
              button={false}
              className={`heading-size-2rem link-hover-parent ${_activeStyleVariant}`}
              fs-list-field={"title"}
              options={link}
            >
              {textTitle}
            </Link>
          </Block>
          <Block
            className={`spacer-0x75rem ${_activeStyleVariant}`}
            tag={"div"}
          />
          <Paragraph
            className={`text-size-1rem ${_activeStyleVariant}`}
            fs-list-field={"desc"}
          >
            {textDesc}
          </Paragraph>
          {locationVisibility ? (
            <Paragraph
              className={`hide ${_activeStyleVariant}`}
              fs-list-field={"location"}
            >
              {location}
            </Paragraph>
          ) : null}
        </Block>
      </Block>
    </div>
  );
}
