/**
 * @generated
 * @file ElementCollectionArticleLink (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";
import Link from "../modules/Basic/components/Link";
import Paragraph from "../modules/Basic/components/Paragraph";

/**
 * Props for {@link ElementCollectionArticleLink}
 */
export type ElementCollectionArticleLinkProps = {
  /** Example : "/en/resources/guides/ai-trends-in-csr"

    Do not forget to update both EN and FR*/
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
};

/**
 * ElementCollectionArticleLink
 *
 */
export function ElementCollectionArticleLink({
  link = {
    href: "#",
  },

  text = "Lorem ipsum dolor sit amet consectetur.",
}: ElementCollectionArticleLinkProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"collection_item"}
        options={link}
      >
        <Paragraph className={"text-size-1x125rem"}>{text}</Paragraph>
        <Block className={"collection_arrow"} tag={"div"}>
          <HtmlEmbed
            className={"icon"}
            content={
              '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M5 12H19" stroke="#130E30" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M12 5L19 12L12 19" stroke="#130E30" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>'
            }
          />
        </Block>
      </Link>
    </div>
  );
}
