/**
 * @generated
 * @file Navbar (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import DOM from "../modules/Builtin/components/DOM";
import DropdownList from "../modules/Dropdown/components/DropdownList";
import DropdownToggle from "../modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "../modules/Dropdown/components/DropdownWrapper";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";
import Image from "../modules/Basic/components/Image";
import Link from "../modules/Basic/components/Link";
import NavbarBrand from "../modules/Navbar/components/NavbarBrand";
import NavbarButton from "../modules/Navbar/components/NavbarButton";
import NavbarContainer from "../modules/Navbar/components/NavbarContainer";
import NavbarLink from "../modules/Navbar/components/NavbarLink";
import NavbarMenu from "../modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "../modules/Navbar/components/NavbarWrapper";
import NotSupported from "../modules/Builtin/components/NotSupported";
import Paragraph from "../modules/Basic/components/Paragraph";
import { Button } from "./Button";
import { Label } from "./Label";

/**
 * Props for {@link Navbar}
 */
export type NavbarProps = {};

/**
 * Navbar
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Collection List`, `Locales Wrapper`
 *
 */
export function Navbar({}: NavbarProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NavbarWrapper
        className={"navbar1"}
        config={{
          easing: "ease",
          easing2: "ease",
          duration: 400,
          docHeight: false,
          noScroll: false,
          animation: "default",
          collapse: "medium",
        }}
        tag={"div"}
      >
        <NavbarContainer className={"navbar_container"} tag={"div"}>
          <Block className={"spacer-1rem"} tag={"div"} />
          <Block className={"navbar1_component"} tag={"div"}>
            <NavbarBrand
              className={"navbar_mobile-brand"}
              options={{
                href: "/en/",
              }}
            >
              <Image
                alt={""}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                }
                width={"120"}
              />
            </NavbarBrand>
            <NavbarMenu
              className={"navbar1_menu"}
              role={"navigation"}
              tag={"nav"}
            >
              <Link
                block={"inline"}
                button={false}
                className={"navbar_brand"}
                options={{
                  href: "/en/",
                }}
              >
                <Image
                  alt={""}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                  }
                  width={"120"}
                />
              </Link>
              <Block className={"navbar1_navigation-list"} tag={"div"}>
                <DropdownWrapper
                  className={"navbar1_dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle className={"navbar1_link"} tag={"div"}>
                    <Block tag={"div"}>{"Frameworks"}</Block>
                    <Block className={"icon-wrapper is-16px"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M3.5312 5.52729C3.79155 5.26694 4.21366 5.26694 4.47401 5.52729L8.0026 9.05589L11.5312 5.52729C11.7915 5.26694 12.2137 5.26694 12.474 5.52729C12.7344 5.78764 12.7344 6.20975 12.474 6.4701L8.47401 10.4701C8.21366 10.7305 7.79155 10.7305 7.5312 10.4701L3.5312 6.4701C3.27085 6.20975 3.27085 5.78764 3.5312 5.52729Z" fill="#130E30"/>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList
                    className={"navbar1_dropdown-small"}
                    tag={"nav"}
                  >
                    <Block className={"dropdown"} tag={"div"}>
                      <Block className={"dropdown1_grid"} tag={"div"}>
                        <Block className={"dropdown_list1"} tag={"div"}>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "/en/frameworks/ecovadis",
                              }}
                            >
                              {"EcoVadis"}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {"Achieve top sustainability ratings"}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "/en/frameworks/iso-14001",
                              }}
                            >
                              {"ISO 14001"}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {"Build a robust environmental management system"}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "/en/frameworks/cdp",
                              }}
                            >
                              {"CDP"}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {"Lead in environmental transparency"}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "/en/frameworks/csrd",
                              }}
                            >
                              {"CSRD / VSME"}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {"Simplify EU sustainability reporting"}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "#",
                              }}
                            >
                              {"Other frameworks"}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {
                                "Showcase your performance across all frameworks"
                              }
                            </Paragraph>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
                <DropdownWrapper
                  className={"navbar1_dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle className={"navbar1_link"} tag={"div"}>
                    <Block tag={"div"}>{"Solutions"}</Block>
                    <Block className={"icon-wrapper is-16px"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M8.50001 8.78145L11.8 5.48145L12.7427 6.42411L8.50001 10.6668L4.25734 6.42411L5.20001 5.48145L8.50001 8.78145Z" fill="#171B26"/>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdow2"} tag={"nav"}>
                    <Block className={"dropdown2_wrapper"} tag={"div"}>
                      <Block className={"dropdown"} tag={"div"}>
                        <Block className={"dropdown1_grid"} tag={"div"}>
                          <Block className={"dropdown_list1"} tag={"div"}>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/solutions/management-system",
                                }}
                              >
                                {"Management system"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Centralize and streamline your CSR efforts"}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/solutions/compliance-questionnaires",
                                }}
                              >
                                {"Compliance questionnaires"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Respond to compliance requests in a flash"}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/solutions/ai-solutions",
                                }}
                              >
                                {"AI solutions"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Your AI-powered CSR co-pilot"}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/solutions/supplier-engagement",
                                }}
                              >
                                {"Supplier engagement"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Engage your supply chain in sustainability"}
                              </Paragraph>
                            </Block>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
                <NavbarLink
                  className={"navbar1_link"}
                  options={{
                    href: "/en/customer-stories",
                  }}
                >
                  {"Customers"}
                </NavbarLink>
                <DropdownWrapper
                  className={"navbar1_dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle className={"navbar1_link"} tag={"div"}>
                    <Block tag={"div"}>{"Resources"}</Block>
                    <Block className={"icon-wrapper is-16px"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M3.5312 5.52729C3.79155 5.26694 4.21366 5.26694 4.47401 5.52729L8.0026 9.05589L11.5312 5.52729C11.7915 5.26694 12.2137 5.26694 12.474 5.52729C12.7344 5.78764 12.7344 6.20975 12.474 6.4701L8.47401 10.4701C8.21366 10.7305 7.79155 10.7305 7.5312 10.4701L3.5312 6.4701C3.27085 6.20975 3.27085 5.78764 3.5312 5.52729Z" fill="#130E30"/>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdown-big"} tag={"nav"}>
                    <Block className={"dropdown-big_wrapper"} tag={"div"}>
                      <Block className={"dropdown"} tag={"div"}>
                        <Block className={"dropdown1_grid _3col"} tag={"div"}>
                          <Block className={"dropdown_list1"} tag={"div"}>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <DOM
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent obflink"
                                }
                                data-o={
                                  "aHR0cHM6Ly93d3cudHJ1c3RkaXR0by5jb20vZW4vcmVzb3VyY2VzL2V2ZW50cw=="
                                }
                                tag={"span"}
                              >
                                {"Webinars"}
                              </DOM>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Watch our past CSR & compliance webinars"}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/collection/ecovadis",
                                }}
                              >
                                {"EcoVadis"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {
                                  "Access resources to succeed in your EcoVadis assessment"
                                }
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/collection/cdp",
                                }}
                              >
                                {"CDP"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {
                                  "Master your CDP assessment with our dedicated resources."
                                }
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/collection/vsme",
                                }}
                              >
                                {"VSME"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {
                                  "Structure your ESG reporting with the VSME standard."
                                }
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/resources",
                                }}
                              >
                                {"See all resources"}
                              </Link>
                            </Block>
                          </Block>
                          <Block className={"dropdown_list1"} tag={"div"}>
                            <Block
                              className={"dropdown_list1_card"}
                              dropdown-parent={"blog"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/resources/blog",
                                }}
                              >
                                {"Blog"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Explore the latest CSR & compliance trends"}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              dropdown-parent={"guides"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/resources/guides",
                                }}
                              >
                                {"Guides"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {
                                  "Access our guides and tools to structure your compliance"
                                }
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              dropdown-parent={"news"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: "/en/resources/news",
                                }}
                              >
                                {"News"}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {"Keep up to date with the latest Ditto news"}
                              </Paragraph>
                            </Block>
                          </Block>
                          <Block
                            className={"dropdown1_grid_content"}
                            tag={"div"}
                          >
                            <NotSupported _atom={"Collection List"} />
                            <NotSupported _atom={"Collection List"} />
                            <NotSupported _atom={"Collection List"} />
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
                <DropdownWrapper
                  className={"navbar1_dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle className={"navbar1_link"} tag={"div"}>
                    <Block tag={"div"}>{"About"}</Block>
                    <Block className={"icon-wrapper is-16px"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M3.5312 5.52729C3.79155 5.26694 4.21366 5.26694 4.47401 5.52729L8.0026 9.05589L11.5312 5.52729C11.7915 5.26694 12.2137 5.26694 12.474 5.52729C12.7344 5.78764 12.7344 6.20975 12.474 6.4701L8.47401 10.4701C8.21366 10.7305 7.79155 10.7305 7.5312 10.4701L3.5312 6.4701C3.27085 6.20975 3.27085 5.78764 3.5312 5.52729Z" fill="#130E30"/>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdow2"} tag={"nav"}>
                    <Block className={"dropdown"} tag={"div"}>
                      <Block className={"dropdown1_grid"} tag={"div"}>
                        <Block className={"dropdown_list1"} tag={"div"}>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "/en/manifesto",
                              }}
                            >
                              {"Manifesto"}
                            </Link>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: "/en/careers",
                              }}
                            >
                              {"Careers"}
                            </Link>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
                <DropdownWrapper
                  className={"navbar_language-dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle
                    className={"navbar_language-dropdown-button"}
                    tag={"div"}
                  >
                    <Block className={"icon-wrapper"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_2319_5414)">\n<path d="M10 19.375C15.1777 19.375 19.375 15.1777 19.375 10C19.375 4.82233 15.1777 0.625 10 0.625C4.82233 0.625 0.625 4.82233 0.625 10C0.625 15.1777 4.82233 19.375 10 19.375Z" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M7.74083 19.1008C6.4725 17.2408 5.625 13.8608 5.625 10C5.625 6.13917 6.4725 2.75917 7.74083 0.89917" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M0.625 10H19.375" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M2.06836 15H17.9317" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M2.06836 5H17.9317" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M12.2588 0.89917C13.5271 2.75917 14.3746 6.13917 14.3746 10C14.3746 13.8608 13.5271 17.2408 12.2588 19.1008" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_2319_5414">\n<rect width="20" height="20" fill="white"/>\n</clipPath>\n</defs>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdow2"} tag={"nav"}>
                    <Block className={"dropdown width-15rem"} tag={"div"}>
                      <Block className={"dropdown1_grid"} tag={"div"}>
                        <Block className={"dropdown_list1"} tag={"div"}>
                          <NotSupported _atom={"Locales Wrapper"} />
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
              </Block>
              <Block className={"navbar_button-group"} tag={"div"}>
                <Block className={"navbar_button"} tag={"div"}>
                  <Button
                    arrow={false}
                    link={{
                      href: "https://cloud.trustditto.com/o",
                      target: "_blank",
                    }}
                    text={"Log in"}
                    variant={"Secondary"}
                  />
                </Block>
                <Block className={"navbar_button"} tag={"div"}>
                  <Button arrow={false} text={"Get Started"} />
                </Block>
              </Block>
            </NavbarMenu>
            <Block className={"navbar1_mobile_button"} tag={"div"}>
              <Button
                arrow={false}
                text={"Get Started"}
                variant={"Primary - Small"}
              />
            </Block>
            <NavbarButton className={"navbar1_menu-button"} tag={"div"}>
              <Block className={"navbar_hamburger"} tag={"div"}>
                <Block className={"navbar_hamburger-line"} tag={"div"} />
                <HtmlEmbed
                  className={"nav_hamburger-embed"}
                  content={
                    "<style>\n.navbar_hamburger {\n\t--thickness: 0.15rem;\n\t--gap: 0.5rem;\n\t--rotate: 45;\n  --width: 70%;\n}\n.w--open .navbar_hamburger-line {\n\twidth: 70% !important;\n\ttransform: scaleX(0);\n}\n.w--open .navbar_hamburger-line:first-child {\n\ttransform: translateY(calc(var(--thickness) + var(--gap))) rotate(calc(var(--rotate) * 3 * 1deg));\n}\n.w--open .navbar_hamburger-line:last-child {\n\ttransform: translateY(calc(var(--thickness) * -1 + var(--gap) * -1)) rotate(calc(var(--rotate) * 1deg));\n}\n</style>"
                  }
                />
                <Block className={"navbar_hamburger-line"} tag={"div"} />
                <Block className={"navbar_hamburger-line"} tag={"div"} />
              </Block>
            </NavbarButton>
          </Block>
          <Block className={"spacer-1rem"} tag={"div"} />
        </NavbarContainer>
        <HtmlEmbed
          className={"paste-to-global"}
          content={
            '<style>\n.navbar1_dropdown .icon-wrapper{\n\ttransition: transform 0.4s ease;\n}\n.navbar1_dropdown:hover .icon-wrapper, .navbar1_dropdown:has(.navbar1_link.w--open) .icon-wrapper{\n\ttransform: rotate(-180deg);\n}\n@media screen and (min-width: 992px){\n  .navbar1_dropdown:hover .navbar1_link.w--open{\n    background-color: var(--_colors-•-semantic---surface-tertiary);\n  }\n  \n  .dropdown1_grid{\n    grid-template-columns: 23.5rem 0rem;\n    transition-property: grid-template-columns;\n    transition-delay: 400ms;\n    transition-duration: 400ms;\n    transition-timing-function: ease-in-out;\n  }\n\n  .navbar1_dropdown-small{\n    left: 0rem;\n  }\n\n  .dropdown1_grid:has([dropdown-accordion="csrd-link"]:hover), .dropdown1_grid:has(.dropdown1_grid_clip:hover) {\n    grid-template-columns: 23.5rem 27rem;\n    transition-delay: 0ms;\n  }\n\n  .navbar1_dropdown-small:has([dropdown-accordion="csrd-link"]){\n    transition-property: left;\n    transition-delay: 400ms;\n    transition-duration: 400ms;\n    transition-timing-function: ease-in-out;\n    left: 0rem;\n  }\n\n  .navbar1_dropdown-small:has([dropdown-accordion="csrd-link"]:hover), .navbar1_dropdown-small:has(.dropdown1_grid_clip:hover){\n    left: -13.5rem;\n    transition-delay: 0ms;\n  }\n}\n\n\n\n\n\n</style>'
          }
        />
      </NavbarWrapper>
    </div>
  );
}
