/**
 * @generated
 * @file NewsletterForm (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import FormButton from "../modules/Form/components/FormButton";
import FormErrorMessage from "../modules/Form/components/FormErrorMessage";
import FormForm from "../modules/Form/components/FormForm";
import FormSuccessMessage from "../modules/Form/components/FormSuccessMessage";
import FormTextInput from "../modules/Form/components/FormTextInput";
import FormWrapper from "../modules/Form/components/FormWrapper";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";

/**
 * Props for {@link NewsletterForm}
 */
export type NewsletterFormProps = {};

/**
 * NewsletterForm
 *
 */
export function NewsletterForm({}: NewsletterFormProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <FormWrapper className={"newsletter_form_wrapper"}>
        <FormForm
          className={"newsletter_form"}
          data-name={"email-form"}
          data-redirect={"https://www.trustditto.com/en/get-started"}
          id={"wf-form-email-form"}
          method={"get"}
          name={"wf-form-email-form"}
          redirect={"https://www.trustditto.com/en/get-started"}
        >
          <Block className={"newsletter_input_wrapper"} tag={"div"}>
            <FormTextInput
              autoFocus={false}
              className={"newsletter_input"}
              data-name={"email"}
              disabled={false}
              id={"email"}
              maxLength={256}
              name={"email"}
              placeholder={"name@company.com"}
              required={true}
              type={"email"}
            />
            <Block className={"button"} id={"submit-button"} tag={"div"}>
              <Block tag={"div"}>{"Get Started"}</Block>
            </Block>
            <FormButton
              className={"button hide"}
              data-wait={"Please wait..."}
              id={"submit"}
              type={"submit"}
              value={"Try Ditto"}
            />
          </Block>
        </FormForm>
        <FormSuccessMessage>
          <Block tag={"div"}>
            {"Thank you! Your submission has been received!"}
          </Block>
        </FormSuccessMessage>
        <FormErrorMessage>
          <Block tag={"div"}>
            {"Oops! Something went wrong while submitting the form."}
          </Block>
        </FormErrorMessage>
        <HtmlEmbed
          className={"section-code"}
          content={
            "<script>\ndocument.addEventListener('DOMContentLoaded', function () {\n    const form = document.getElementById('wf-form-email-form');\n    const emailInput = document.getElementById('email');\n    const fakeSubmitButton = document.getElementById('submit-button');\n    const realSubmitButton = document.getElementById('submit');\n\n    // Function to store email and submit\n    const storeAndSubmit = () => {\n        const emailValue = emailInput.value.trim();\n        if (emailValue) {\n            localStorage.setItem('userEmail', emailValue);\n        }\n        realSubmitButton.click();\n    };\n\n    // 1️⃣ Handle click on fake button\n    fakeSubmitButton.addEventListener('click', function () {\n        storeAndSubmit();\n    });\n\n    // 2️⃣ Handle \"Enter\" key on input fields\n    form.addEventListener('keydown', function (e) {\n        if (e.key === 'Enter') {\n            e.preventDefault(); // prevent default form submission\n            storeAndSubmit();\n        }\n    });\n});\n</script>"
          }
        />
      </FormWrapper>
    </div>
  );
}
