/**
 * @generated
 * @file SectionHero (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Image from "../webflow_modules/Basic/components/Image";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { ElementSocialproofTrustpilot } from "../elements/ElementSocialproofTrustpilot";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionHero}
 */
export type SectionHeroProps = {
  buttonLeft?: React.ReactNode;
  buttonRight?: React.ReactNode;
  buttonsVisibility?: boolean;
  image?: string;
  paddingBottom?: "Small (3rem)" | "Medium (6rem)" | "Large (9rem)" | "None";
  paragraph?: React.ReactNode;
  title?: React.ReactNode;
  variant?: "Base" | "Heading 4rem";
};

/**
 * SectionHero
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionHero({
  buttonLeft,
  buttonRight,
  buttonsVisibility = true,
  image = "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682d7fad3c89203197a56fb7_image.svg",
  paddingBottom = "Small (3rem)",
  paragraph = "Ditto helps you structure your CSR approach and complete the EcoVadis assessment with ease, so you get the medal you deserve each year.",
  title = "lorem ipsum",
  variant = "Base",
}: SectionHeroProps) {
  const _styleVariantMap = {
    Base: "",
    "Heading 4rem": "w-variant-234d20b7-ade1-a378-0a62-2b94b0af6325",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`hero_section ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        id={"w-node-_5376df0c-86b4-ec34-ffe0-9997d93952dc-d93952dc"}
        tag={"section"}
      >
        <Block className={`padding-global ${_activeStyleVariant}`} tag={"div"}>
          <Padding space={"None"} />
          <Block
            className={`container-84rem ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`hero_component ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`hero_content ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Heading
                  className={`heading-size-3rem ${_activeStyleVariant}`}
                  tag={"h1"}
                >
                  {title}
                </Heading>
                <Block
                  className={`spacer-1x5rem ${_activeStyleVariant}`}
                  tag={"div"}
                />
                <Paragraph
                  className={`text-size-1x375rem ${_activeStyleVariant}`}
                >
                  {paragraph}
                </Paragraph>
                {buttonsVisibility ? (
                  <Block
                    className={`spacer-1x5rem spacer-mob-1rem ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                ) : null}
                {buttonsVisibility ? (
                  <Block
                    className={`button-group ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    {buttonLeft}
                    {buttonRight}
                  </Block>
                ) : null}
                <Block
                  className={`spacer-1x5rem spacer-mob-1rem ${_activeStyleVariant}`}
                  tag={"div"}
                />
                <ElementSocialproofTrustpilot />
              </Block>
              <Block
                className={`hero_image_wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Image
                  alt={""}
                  className={`hero_image ${_activeStyleVariant}`}
                  height={"auto"}
                  loading={"lazy"}
                  src={image}
                  width={"auto"}
                />
              </Block>
            </Block>
          </Block>
          <Padding space={paddingBottom} />
        </Block>
        <Block className={`layer-4 ${_activeStyleVariant}`} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
