/**
 * @generated
 * @file SectionFeaturesHeader (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionFeaturesHeader}
 */
export type SectionFeaturesHeaderProps = {
  text?: React.ReactNode;
  textVisibility?: boolean;
  title?: React.ReactNode;
};

/**
 * SectionFeaturesHeader
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionFeaturesHeader({
  text = "Lorem ipsum",
  textVisibility = true,
  title = "Lorem ipsum",
}: SectionFeaturesHeaderProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"generic_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-e144229d-054e-2471-9911-566cb243596f-b243596f"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-55rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {title}
              </Heading>
              {textVisibility ? (
                <Block className={"spacer-1x5rem"} tag={"div"} />
              ) : null}
              {textVisibility ? (
                <Paragraph className={"text-size-1x375rem text-wrap-balance"}>
                  {text}
                </Paragraph>
              ) : null}
            </Block>
          </Block>
          <Padding space={"None"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
