/**
 * @generated
 * @file SectionCareersIntro (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { Button } from "../elements/Button";
import { Label } from "../elements/Label";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionCareersIntro}
 */
export type SectionCareersIntroProps = {};

/**
 * SectionCareersIntro
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionCareersIntro({}: SectionCareersIntroProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"careers-intro_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_432cdc1b-2f73-ddb5-ea63-5dc7aeabfc88-aeabfc88"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"show-tablet"} tag={"div"}>
            <Padding space={"Large (9rem)"} />
          </Block>
          <Block className={"container-64rem"} tag={"div"}>
            <Block className={"careers-intro_component"} tag={"div"}>
              <Block className={"careers-intro_image_wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"media-full-size"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6835b2bf2bcf770c96ef396c_manifesto.avif"
                  }
                  width={"auto"}
                />
              </Block>
              <Block className={"careers-intro_content_wrapper"} tag={"div"}>
                <Label label={"Careers"} />
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <Heading className={"heading-size-3rem"} tag={"h2"}>
                  {"We’re all copilots on this journey"}
                </Heading>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <Paragraph className={"text-size-1x375rem"}>
                  {
                    "This work is about building better together—and that starts with our team. If you want to work on the future of sustainable business, we’d love to hear from you."
                  }
                </Paragraph>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <Block className={"button-group"} tag={"div"}>
                  <Button
                    arrow={false}
                    link={{
                      href: "/en/careers",
                    }}
                    text={"Explore open roles"}
                  />
                </Block>
              </Block>
              <HtmlEmbed
                className={"careers-intro_side_left hide-tablet"}
                content={
                  '<svg width="100%" height="100%" viewBox="0 0 322 501" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<rect width="139" height="500" rx="64.1127" transform="matrix(-1 0 0 1 139.734 0.941406)" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="74.0938" y="20.9414" width="247.166" height="459.296" rx="123.583" fill="#59E25D"/>\n</g>\n</svg>'
                }
              />
              <HtmlEmbed
                className={"careers-intro_side_left"}
                content={
                  '<svg width="330" height="196" viewBox="0 0 330 196" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<path d="M290 80.5C312.091 80.5 330 62.5914 330 40.5V40.5C330 18.4086 312.091 0.500012 290 0.50001L129 0.500002C106.909 0.500001 89 18.4086 89 40.5V40.5C89 62.5914 106.909 80.5 129 80.5L290 80.5Z" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<path d="M228 55.5C266.66 55.5 298 86.8401 298 125.5V125.5C298 164.16 266.66 195.5 228 195.5L70 195.5C31.3401 195.5 1.56921e-06 164.16 3.50492e-06 125.5V125.5C5.44063e-06 86.8401 31.3401 55.5 70 55.5L228 55.5Z" fill="#59E25D"/>\n</g>\n</svg>'
                }
              />
              <HtmlEmbed
                className={"careers-intro_side_right hide-tablet"}
                content={
                  '<svg width="217" height="471" viewBox="0 0 217 471" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<rect width="216.043" height="470.495" rx="108.021" fill="#E261E5"/>\n</g>\n</svg>'
                }
              />
              <HtmlEmbed
                className={"careers-intro_side_right show-tablet"}
                content={
                  '<svg width="326" height="141" viewBox="0 0 326 141" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<path d="M70 140.5C31.3401 140.5 0 109.16 0 70.5V70.5C0 31.8401 31.3401 0.5 70 0.5H256C294.66 0.5 326 31.8401 326 70.5V70.5C326 109.16 294.66 140.5 256 140.5H70Z" fill="#E261E5"/>\n</g>\n</svg>'
                }
              />
            </Block>
            <Block tag={"div"} />
          </Block>
          <Block className={"show-tablet"} tag={"div"}>
            <Padding space={"Medium (6rem)"} />
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
