/**
 * @generated
 * @file SectionNumbers (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionNumbers}
 */
export type SectionNumbersProps = {
  card1Card1Number?: React.ReactNode;
  card1Card1Text?: React.ReactNode;
  card2Card2Number?: React.ReactNode;
  card2Card2Text?: React.ReactNode;
  card3Card3Number?: React.ReactNode;
  card3Card3Text?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * SectionNumbers
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionNumbers({
  card1Card1Number = "123+",
  card1Card1Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  card2Card2Number = "123+",
  card2Card2Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  card3Card3Number = "123+",
  card3Card3Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  title = "Lorem ipsum",
}: SectionNumbersProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"numbers_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-e102153d-b8a3-8ff4-bf44-bfd6b093504b-b093504b"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {title}
              </Heading>
            </Block>
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block className={"numbers_list"} tag={"div"}>
              <Block className={"numbers_card"} tag={"div"}>
                <Paragraph className={"heading-size-display"}>
                  {card1Card1Number}
                </Paragraph>
                <Paragraph className={"text-size-1x375rem"}>
                  {card1Card1Text}
                </Paragraph>
              </Block>
              <Block className={"numbers_card is--blue"} tag={"div"}>
                <Paragraph className={"heading-size-display"}>
                  {card2Card2Number}
                </Paragraph>
                <Paragraph className={"text-size-1x375rem"}>
                  {card2Card2Text}
                </Paragraph>
              </Block>
              <Block className={"numbers_card is--green"} tag={"div"}>
                <Paragraph className={"heading-size-display"}>
                  {card3Card3Number}
                </Paragraph>
                <Paragraph className={"text-size-1x375rem"}>
                  {card3Card3Text}
                </Paragraph>
              </Block>
            </Block>
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block className={"button-group x-center"} tag={"div"} />
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
