/**
 * @generated
 * @file SectionCtaPill (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { Button } from "../elements/Button";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionCtaPill}
 */
export type SectionCtaPillProps = {};

/**
 * SectionCtaPill
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionCtaPill({}: SectionCtaPillProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"cta-pill_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_6406cb4e-0c86-4c42-f1d6-e4dda1206d93-a1206d93"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"cta-pill_component"} tag={"div"}>
              <Block className={"cta-pill_content"} tag={"div"}>
                <Heading className={"heading-size-3rem"} tag={"h2"}>
                  {"One platform to power your progress"}
                </Heading>
                <Block className={"max-width-50rem"} tag={"div"}>
                  <Paragraph className={"text-size-1x375rem"}>
                    {
                      "Ditto gives you the insights and tools to transform your CSR program. So you can feel confident when it’s time for certification and feel ready for your next RFP."
                    }
                  </Paragraph>
                </Block>
                <Button arrow={false} text={"Get Started"} />
              </Block>
              <HtmlEmbed
                className={"cta-pill_left"}
                content={
                  '<svg width="100%" height="100%" viewBox="0 0 1120 238" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<rect width="224.495" height="220.02" rx="110.01" transform="matrix(-1 0 0 1 224.492 9.07031)" fill="#E261E5"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="371.11" height="220.02" rx="110.01" transform="matrix(-1 0 0 1 1022.45 9.07031)" fill="#59E25D"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="456.008" y="0.757812" width="235.199" height="236.908" rx="117.599" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="392.156" y="33.4453" width="99.6043" height="171.543" rx="49.8022" fill="#59E25D"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="450.288" height="236.907" rx="118.454" transform="matrix(-1 0 0 1 587.008 0.757812)" fill="#FFE228"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="167.631" height="236.907" rx="83.8156" transform="matrix(-1 0 0 1 1119.19 0.757812)" fill="#E261E5"/>\n</g>\n</svg>'
                }
              />
              <HtmlEmbed
                className={"cta-pill_right"}
                content={
                  '<svg width="100%" height="100%" viewBox="0 0 1120 264" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<rect width="224" height="219" rx="109.5" transform="matrix(-1 0 0 1 224 22.5)" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="450" height="263" rx="131.5" transform="matrix(-1 0 0 1 587 0.5)" fill="#E261E5"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="371.11" height="220.02" rx="110.01" transform="matrix(-1 0 0 1 1022.45 22.0703)" fill="#59E25D"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="456.008" y="13.7578" width="235.199" height="236.908" rx="117.599" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="392.156" y="46.4453" width="99.6043" height="171.543" rx="49.8022" fill="#59E25D"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="167.631" height="236.907" rx="83.8156" transform="matrix(-1 0 0 1 1119.19 13.7578)" fill="#E261E5"/>\n</g>\n</svg>'
                }
              />
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
