/**
 * @generated
 * @file SectionCarouselCustom (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionCarouselCustom}
 */
export type SectionCarouselCustomProps = {
  slot1Slot1?: React.ReactNode;
  slot1Slot1Visible?: boolean;
  slot2Slot2?: React.ReactNode;
  slot2Slot2Visible?: boolean;
  slot3Slot3?: React.ReactNode;
  slot3Slot3Visible?: boolean;
  slot4Slot4?: React.ReactNode;
  slot4Slot4Visible?: boolean;
  slot5Slot5?: React.ReactNode;
  slot5Slot5Visible?: boolean;
  slot6Slot6?: React.ReactNode;
  slot6Slot6Visible?: boolean;
  slot7Slot7?: React.ReactNode;
  slot7Slot7Visible?: boolean;
  slot8Slot8?: React.ReactNode;
  slot8Slot8Visible?: boolean;
  title?: React.ReactNode;
};

/**
 * SectionCarouselCustom
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionCarouselCustom({
  slot1Slot1,
  slot1Slot1Visible = true,
  slot2Slot2,
  slot2Slot2Visible = true,
  slot3Slot3,
  slot3Slot3Visible = true,
  slot4Slot4,
  slot4Slot4Visible = true,
  slot5Slot5,
  slot5Slot5Visible = false,
  slot6Slot6,
  slot6Slot6Visible = false,
  slot7Slot7,
  slot7Slot7Visible = false,
  slot8Slot8,
  slot8Slot8Visible = false,
  title = "Lorem ipsum",
}: SectionCarouselCustomProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"carousel_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_10e6beb8-c0b2-7c69-4594-8e0825270955-25270955"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"max-width-32rem"} tag={"div"} />
            <Heading
              className={"heading-size-3rem text-wrap-balance"}
              tag={"h2"}
            >
              {title}
            </Heading>
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block
              className={"carousel_component"}
              // @ts-ignore - User-defined custom attribute(s)
              splide={"carousel"}
              splide-direction={"ltr"}
              splide-gap={"3rem"}
              splide-gap-mobile={"1rem"}
              splide-interval={"5000"}
              tag={"div"}
            >
              <Block className={"carousel_splide_wrapper"} tag={"div"}>
                <Block
                  className={"carousel_splide splide width-26rem"}
                  tag={"div"}
                >
                  <Block className={"carousel_track splide__track"} tag={"div"}>
                    <Block
                      className={"carousel_list splide__list designer"}
                      tag={"div"}
                    >
                      {slot1Slot1}
                      {slot2Slot2}
                      {slot3Slot3}
                      {slot4Slot4}
                      {slot5Slot5}
                      {slot6Slot6}
                      {slot7Slot7}
                      {slot8Slot8}
                    </Block>
                  </Block>
                </Block>
                <Block className={"carousel_navigation_wrapper"} tag={"div"} />
              </Block>
              <Block className={"spacer-1x5rem"} tag={"div"} />
              <Block className={"carousel_pagination_list"} tag={"div"}>
                <Block
                  className={"carousel_pagination_button"}
                  splide-button={"pagination"}
                  tag={"div"}
                />
                <Block
                  className={"carousel_pagination_button is-active"}
                  tag={"div"}
                />
              </Block>
            </Block>
          </Block>
          <Padding space={"None"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
