/**
 * @generated
 * @file SectionFeature (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Image from "../webflow_modules/Basic/components/Image";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import { Background } from "../Background";
import { Button } from "../elements/Button";
import { Label } from "../elements/Label";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionFeature}
 */
export type SectionFeatureProps = {
  buttonButtonLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonButtonText?: React.ReactNode;
  buttonButtonVisibility?: boolean;
  image?: string;
  labelLabelText?: React.ReactNode;
  labelLabelVisibility?: boolean;
  paragraph?: React.ReactNode;
  title?: React.ReactNode;
  variant?:
    | "Layout • Base"
    | "Layout • Reversed"
    | "Image • Overflow"
    | "Title • Bigger"
    | "Layout • Reversed + Title • Bigger";
};

/**
 * SectionFeature
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionFeature({
  buttonButtonLink = {
    href: "#",
  },

  buttonButtonText = "Learn More",
  buttonButtonVisibility = true,
  image = "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682d7fad3c89203197a56fb7_image.svg",
  labelLabelText = "Lorem ipsum",
  labelLabelVisibility = true,
  paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  title = "Lorem Ipsum",
  variant = "Layout • Base",
}: SectionFeatureProps) {
  const _styleVariantMap = {
    "Layout • Base": "",
    "Layout • Reversed": "w-variant-36516e33-6498-7739-c387-daf79718e851",
    "Image • Overflow": "w-variant-4ebb32a8-1af6-b01a-98eb-4cf2c5559d60",
    "Title • Bigger": "w-variant-6f990363-6fa9-05c1-512a-814640ca9882",
    "Layout • Reversed + Title • Bigger":
      "w-variant-eb7b6165-37c2-e37d-3cda-433460ed5cd9",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`feature1_section ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        id={"w-node-a5ec71fe-25f3-a031-1282-1b8038916485-38916485"}
        tag={"section"}
      >
        <Block className={`padding-global ${_activeStyleVariant}`} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block
            className={`container-84rem ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`feature_component ${_activeStyleVariant}`}
              tag={"div"}
            >
              <Block
                className={`feature_content_wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`feature_content ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  {labelLabelVisibility ? (
                    <Block
                      className={`label_wrapper ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Label label={labelLabelText} />
                    </Block>
                  ) : null}
                  {labelLabelVisibility ? (
                    <Block
                      className={`spacer-1x5rem ${_activeStyleVariant}`}
                      tag={"div"}
                    />
                  ) : null}
                  <Heading
                    className={`heading-size-2rem ${_activeStyleVariant}`}
                    tag={"h2"}
                  >
                    {title}
                  </Heading>
                  <Block
                    className={`spacer-1x5rem ${_activeStyleVariant}`}
                    tag={"div"}
                  />
                  <Paragraph
                    className={`text-size-1x375rem ${_activeStyleVariant}`}
                  >
                    {paragraph}
                  </Paragraph>
                  {buttonButtonVisibility ? (
                    <Block
                      className={`spacer-1x5rem ${_activeStyleVariant}`}
                      tag={"div"}
                    />
                  ) : null}
                  {buttonButtonVisibility ? (
                    <Block
                      className={`button-group ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Button
                        arrow={false}
                        link={buttonButtonLink}
                        text={buttonButtonText}
                        variant={"Secondary"}
                      />
                    </Block>
                  ) : null}
                </Block>
              </Block>
              <Block
                className={`feature_image_wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Image
                  alt={""}
                  className={`feature_image ${_activeStyleVariant}`}
                  height={"auto"}
                  loading={"lazy"}
                  src={image}
                  width={"auto"}
                />
              </Block>
            </Block>
          </Block>
          <Padding space={"None"} />
        </Block>
        <Block className={`layer-4 ${_activeStyleVariant}`} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
