/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import posthog from "posthog-js";
import { useState, useCallback, useEffect } from "react";
import { useLocale, useTranslations } from "next-intl";
import { usePathname } from "next/navigation";
import { switchLocalePath, localizedHref, localizedCmsHref } from "../lib/localized-paths";
import { useAlternateUrls } from "./AlternateUrlContext";
import { DEVLINK_SCOPE_CLASS } from "../../devlink/devlinkScope";
import Block from "../../devlink/modules/Basic/components/Block";
import DOM from "../../devlink/modules/Builtin/components/DOM";
import HtmlEmbed from "../../devlink/modules/Embed/components/HtmlEmbed";
import Image from "../../devlink/modules/Basic/components/Image";
import Link from "../../devlink/modules/Basic/components/Link";
import { getBlogPosts, getNews } from "../lib/cms";
import Paragraph from "../../devlink/modules/Basic/components/Paragraph";
import Section from "../../devlink/modules/Layout/components/Section";
import { Background } from "../../devlink/Background";
import { ElementSocialproofTrustpilot } from "../../devlink/elements/ElementSocialproofTrustpilot";
import { Padding } from "../../devlink/Padding";

// Portal ID is numeric, form ID is the HubSpot form UUID
const HUBSPOT_PORTAL_ID = process.env.NEXT_PUBLIC_HUBSPOT_PORTAL_ID_CONTACT!;
const HUBSPOT_FORM_ID = process.env.NEXT_PUBLIC_HUBSPOT_FORM_ID!;

function FooterNewsletter() {
  const locale = useLocale();
  const isFr = locale === "fr";
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");

  const handleSubmit = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || status === "loading") return;

    setStatus("loading");
    try {
      const res = await fetch(
        `https://api.hsforms.com/submissions/v3/integration/submit/${HUBSPOT_PORTAL_ID}/${HUBSPOT_FORM_ID}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            fields: [{ name: "email", value: email }],
            context: {
              pageUri: typeof window !== "undefined" ? window.location.href : "",
              pageName: "Footer Newsletter",
            },
          }),
        }
      );
      if (res.ok) {
        setStatus("success");
        try { posthog.capture("newsletter_subscribed", { placement: "footer" }); } catch {}
        setEmail("");
      } else {
        setStatus("error");
      }
    } catch {
      setStatus("error");
    }
  }, [email, status]);

  return (
    <Block className={"footer_newsletter"} tag={"div"}>
      <Paragraph className={"text-size-1rem text-weight-600 text-wrap-balance"}>
        {isFr ? "Abonnez-vous \u00e0 notre newsletter RSE\u00a0: \u00e9tudes, cas concrets, outils" : "Practical CSR insights\u2014tools, studies, and templates, in your inbox"}
      </Paragraph>
      {status === "success" ? (
        <Block className={"newsletter_form_wrapper"} tag={"div"}>
          <div className="newsletter_form_success w-form-done" style={{ display: "block" }}>
            <div>{isFr ? "Merci pour votre inscription !" : "Thank you for subscribing!"}</div>
          </div>
        </Block>
      ) : (
        <Block className={"newsletter_form_wrapper"} tag={"div"}>
          <form className="newsletter_form" onSubmit={handleSubmit}>
            <div className="newsletter_input_wrapper">
              <input
                className="newsletter_input w-input"
                maxLength={256}
                name="email"
                placeholder="name@company.com"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <input
                type="submit"
                className="button w-button"
                value={status === "loading" ? (isFr ? "Veuillez patienter..." : "Please wait...") : (isFr ? "S'inscrire" : "Subscribe")}
                disabled={status === "loading"}
              />
            </div>
          </form>
          {status === "error" && (
            <div className="w-form-fail" style={{ display: "block" }}>
              <div>{isFr ? "Oups ! Une erreur est survenue lors de l'envoi du formulaire." : "Oops! Something went wrong while submitting the form."}</div>
            </div>
          )}
        </Block>
      )}
    </Block>
  );
}

/**
 * Props for {@link Footer}
 */
export type FooterProps = {
  blogPosts?: any[];
  newsItems?: any[];
  alternateUrls?: Record<string, string>;
};

/**
 * Footer
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Locales Wrapper`, `Collection List`
 *
 */
export function FooterClient({ blogPosts: serverBlogPosts, newsItems: serverNewsItems, alternateUrls }: FooterProps) {
  const locale = useLocale();
  const pathname = usePathname();
  const { urls: contextUrls } = useAlternateUrls();
  const resolvedAlternateUrls = alternateUrls || contextUrls;
  const t = useTranslations("footer");
  const tNav = useTranslations("nav");
  const [clientBlogPosts, setClientBlogPosts] = useState<any[]>(serverBlogPosts || []);
  const [clientNewsItems, setClientNewsItems] = useState<any[]>(serverNewsItems || []);

  useEffect(() => {
    if (serverBlogPosts && serverNewsItems) return;
    if (!serverBlogPosts) {
      getBlogPosts(locale as "en" | "fr", 4)
        .then((data) => setClientBlogPosts(data || []))
        .catch(() => {});
    }
    if (!serverNewsItems) {
      getNews(locale as "en" | "fr", 4)
        .then((data) => setClientNewsItems(data || []))
        .catch(() => {});
    }
  }, [locale, serverBlogPosts, serverNewsItems]);

  const blogPosts = serverBlogPosts || clientBlogPosts;
  const newsItems = serverNewsItems || clientNewsItems;
  const prefix = `/${locale}`;

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"footer"}
        grid={{
          type: "section",
        }}
        id={"w-node-e77519be-32ac-35f9-e6e2-a8620379ed03-0379ed03"}
        tag={"footer"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"None"} />
          <Block className={"container-84rem"} tag={"div"}>
            <FooterNewsletter />
          </Block>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"footer_component"} tag={"div"}>
              <Block className={"footer_brand"} tag={"div"}>
                <Link
                  block={"inline"}
                  button={false}
                  className={"footer_linkblock"}
                  options={{
                    href: `${prefix}/`,
                  }}
                >
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                    }
                    width={"120"}
                  />
                </Link>
                <Block className={"spacer-1rem"} tag={"div"}>
                  <Block className={"spacer-0x25rem"} tag={"div"} />
                </Block>
                <Paragraph className={"heading-size-1x375rem"}>
                  {t("tagline")}
                </Paragraph>
                <Block className={"spacer-2rem"} tag={"div"} />
                <ElementSocialproofTrustpilot />
                <Block className={"spacer-2rem"} tag={"div"} />
                <Block className={"footer_socials_list"} tag={"div"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"socials_link"}
                    options={{
                      href: "https://www.linkedin.com/company/trustditto/",
                      target: "_blank",
                    }}
                  >
                    <HtmlEmbed
                      className={"icon"}
                      content={
                        '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_305_5063)">\n<path d="M18.5195 0H1.47656C0.660156 0 0 0.644531 0 1.44141V18.5547C0 19.3516 0.660156 20 1.47656 20H18.5195C19.3359 20 20 19.3516 20 18.5586V1.44141C20 0.644531 19.3359 0 18.5195 0ZM5.93359 17.043H2.96484V7.49609H5.93359V17.043ZM4.44922 6.19531C3.49609 6.19531 2.72656 5.42578 2.72656 4.47656C2.72656 3.52734 3.49609 2.75781 4.44922 2.75781C5.39844 2.75781 6.16797 3.52734 6.16797 4.47656C6.16797 5.42188 5.39844 6.19531 4.44922 6.19531ZM17.043 17.043H14.0781V12.4023C14.0781 11.2969 14.0586 9.87109 12.5352 9.87109C10.9922 9.87109 10.7578 11.0781 10.7578 12.3242V17.043H7.79688V7.49609H10.6406V8.80078H10.6797C11.0742 8.05078 12.043 7.25781 13.4844 7.25781C16.4883 7.25781 17.043 9.23438 17.043 11.8047V17.043Z" fill="#130E30"/>\n</g>\n<defs>\n<clipPath id="clip0_305_5063">\n<rect width="20" height="20" fill="white"/>\n</clipPath>\n</defs>\n</svg>'
                      }
                    />
                  </Link>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"socials_link"}
                    options={{
                      href: "https://www.youtube.com/@trustditto",
                      target: "_blank",
                    }}
                  >
                    <HtmlEmbed
                      className={"icon"}
                      content={
                        '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M19.582 5.188a2.513 2.513 0 0 0-1.768-1.78C16.254 3 10 3 10 3s-6.254 0-7.814.408A2.513 2.513 0 0 0 .418 5.188C0 6.758 0 10.024 0 10.024s0 3.266.418 4.836a2.513 2.513 0 0 0 1.768 1.78C3.746 17.048 10 17.048 10 17.048s6.254 0 7.814-.408a2.513 2.513 0 0 0 1.768-1.78C20 13.29 20 10.024 20 10.024s0-3.266-.418-4.836ZM7.976 13.048V7l5.227 3.024L7.976 13.048Z" fill="#130E30"/></svg>'
                      }
                    />
                  </Link>
                  <Block className={"w-locales-list"} tag={"div"}>
                    <Block className={"w-locales-items"} tag={"div"} role={"list"}>
                      <Block className={"w-locales-item"} tag={"div"} role={"listitem"}>
                        <Link block={""} button={false} options={{ href: resolvedAlternateUrls["en"] || switchLocalePath(pathname, "en") }}>
                          {"English"}
                        </Link>
                      </Block>
                      <Block className={"w-locales-item"} tag={"div"} role={"listitem"}>
                        <Link block={""} button={false} options={{ href: resolvedAlternateUrls["fr"] || switchLocalePath(pathname, "fr") }}>
                          {"Français"}
                        </Link>
                      </Block>
                    </Block>
                  </Block>
                </Block>
                <Block className={"spacer-2rem"} tag={"div"} />
                <Block className={"footer_legal_list"} tag={"div"}>
                  <Paragraph className={"text-size-0x875rem text-weight-600"}>
                    {t("copyright", { year: new Date().getFullYear() })}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"text-size-0x875rem"}
                    options={{
                      href: localizedHref("/legal/terms-and-conditions", locale),
                    }}
                  >
                    {t("terms")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"text-size-0x875rem"}
                    options={{
                      href: localizedHref("/legal/privacy-policy", locale),
                    }}
                  >
                    {t("privacy")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"text-size-0x875rem"}
                    options={{
                      href: localizedHref("/legal/legal-notices", locale),
                    }}
                  >
                    {t("legal")}
                  </Link>
                </Block>
              </Block>
              <Block className={"footer_navigation"} tag={"nav"}>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {t("frameworks")}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/frameworks/ecovadis`,
                    }}
                  >
                    {"EcoVadis"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/frameworks/cdp`,
                    }}
                  >
                    {"CDP"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/frameworks/csrd`,
                    }}
                  >
                    {"CSRD"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/frameworks/iso-14001`,
                    }}
                  >
                    {"ISO 14001"}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {t("solutions")}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/solutions/management-system`,
                    }}
                  >
                    {tNav("managementSystem")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/solutions/compliance-questionnaires`,
                    }}
                  >
                    {tNav("complianceQuestionnaires")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/solutions/ai-solutions`,
                    }}
                  >
                    {tNav("aiSolutions")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/solutions/supplier-engagement`,
                    }}
                  >
                    {tNav("supplierEngagement")}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {t("customers")}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/customer-stories", locale) + "?team-size_equal=100-250",
                    }}
                  >
                    {t("sme")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/customer-stories", locale) + "?team-size_equal=1000-5000",
                    }}
                  >
                    {t("largeCompanies")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/customer-stories", locale),
                    }}
                  >
                    {t("allCaseStudies")}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {t("resources")}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/resources", locale),
                    }}
                  >
                    {t("all")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/resources/blog", locale),
                    }}
                  >
                    {tNav("blog")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/resources/news", locale),
                    }}
                  >
                    {tNav("news")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: localizedHref("/resources/guides", locale),
                    }}
                  >
                    {tNav("guides")}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `https://app.livestorm.co/trustditto?lang=${locale}`,
                      target: "_blank",
                    }}
                  >
                    {t("events")}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {t("about")}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: `${prefix}/manifesto`,
                    }}
                  >
                    {tNav("manifesto")}
                  </Link>
                  <DOM
                    className={"link-size-1rem obflink"}
                    data-o={
                      "aHR0cHM6Ly93d3cudHJ1c3RkaXR0by5jb20vZW4vY2FyZWVycw=="
                    }
                    tag={"span"}
                  >
                    {tNav("careers")}
                  </DOM>
                </Block>
                <Block
                  className={"footer_navigation_col width-20rem"}
                  tag={"div"}
                >
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {tNav("blog")}
                  </Paragraph>
                  {blogPosts.map((post) => (
                    <Link
                      key={post.id}
                      block={""}
                      button={false}
                      className={"link-size-1rem"}
                      options={{ href: localizedCmsHref("/resources/blog", post.slug, post.slug_fr, locale) }}
                    >
                      {post.name}
                    </Link>
                  ))}
                </Block>
                <Block
                  className={"footer_navigation_col width-20rem"}
                  tag={"div"}
                >
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {tNav("news")}
                  </Paragraph>
                  {newsItems.map((item) => (
                    <Link
                      key={item.id}
                      block={""}
                      button={false}
                      className={"link-size-1rem"}
                      options={{ href: localizedCmsHref("/resources/news", item.slug, item.slug_fr, locale) }}
                    >
                      {item.name}
                    </Link>
                  ))}
                </Block>
              </Block>
            </Block>
          </Block>
          <Padding space={"Small (3rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
