/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { useState, useCallback, useEffect } from "react";
import { useLocale } from "next-intl";
import { DEVLINK_SCOPE_CLASS } from "../../webflow/devlinkScope";
import Block from "../../webflow/webflow_modules/Basic/components/Block";
import DOM from "../../webflow/webflow_modules/Builtin/components/DOM";
import FormButton from "../../webflow/webflow_modules/Form/components/FormButton";
import FormErrorMessage from "../../webflow/webflow_modules/Form/components/FormErrorMessage";
import FormForm from "../../webflow/webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "../../webflow/webflow_modules/Form/components/FormSuccessMessage";
import FormTextInput from "../../webflow/webflow_modules/Form/components/FormTextInput";
import FormWrapper from "../../webflow/webflow_modules/Form/components/FormWrapper";
import HtmlEmbed from "../../webflow/webflow_modules/Embed/components/HtmlEmbed";
import Image from "../../webflow/webflow_modules/Basic/components/Image";
import Link from "../../webflow/webflow_modules/Basic/components/Link";
import { getBlogPosts, getNews } from "../lib/cms";
import Paragraph from "../../webflow/webflow_modules/Basic/components/Paragraph";
import Section from "../../webflow/webflow_modules/Layout/components/Section";
import { Background } from "../../webflow/Background";
import { ElementSocialproofTrustpilot } from "../../webflow/elements/ElementSocialproofTrustpilot";
import { Padding } from "../../webflow/Padding";

const HUBSPOT_PORTAL_ID = process.env.NEXT_PUBLIC_HUBSPOT_PORTAL_ID!;
const HUBSPOT_FORM_ID = process.env.NEXT_PUBLIC_HUBSPOT_FORM_ID!;

function FooterNewsletter() {
  const locale = useLocale();
  const isFr = locale === "fr";
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle");

  const handleSubmit = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || status === "loading") return;

    setStatus("loading");
    try {
      const res = await fetch(
        `https://api.hsforms.com/submissions/v3/integration/submit/${HUBSPOT_PORTAL_ID}/${HUBSPOT_FORM_ID}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            fields: [{ name: "email", value: email }],
            context: {
              pageUri: typeof window !== "undefined" ? window.location.href : "",
              pageName: "Footer Newsletter",
            },
          }),
        }
      );
      if (res.ok) {
        setStatus("success");
        setEmail("");
      } else {
        setStatus("error");
      }
    } catch {
      setStatus("error");
    }
  }, [email, status]);

  return (
    <Block className={"footer_newsletter"} tag={"div"}>
      <Paragraph className={"text-size-1rem text-weight-600 text-wrap-balance"}>
        {isFr ? "Abonnez-vous \u00e0 notre newsletter RSE\u00a0: \u00e9tudes, cas concrets, outils" : "Practical CSR insights\u2014tools, studies, and templates, in your inbox"}
      </Paragraph>
      {status === "success" ? (
        <Block className={"newsletter_form_wrapper"} tag={"div"}>
          <div className="newsletter_form_success w-form-done" style={{ display: "block" }}>
            <div>{isFr ? "Merci pour votre inscription !" : "Thank you for subscribing!"}</div>
          </div>
        </Block>
      ) : (
        <Block className={"newsletter_form_wrapper"} tag={"div"}>
          <form className="newsletter_form" onSubmit={handleSubmit}>
            <div className="newsletter_input_wrapper">
              <input
                className="newsletter_input w-input"
                maxLength={256}
                name="email"
                placeholder="name@company.com"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <input
                type="submit"
                className="button w-button"
                value={status === "loading" ? (isFr ? "Veuillez patienter..." : "Please wait...") : (isFr ? "S'inscrire" : "Subscribe")}
                disabled={status === "loading"}
              />
            </div>
          </form>
          {status === "error" && (
            <div className="w-form-fail" style={{ display: "block" }}>
              <div>{isFr ? "Oups ! Une erreur est survenue lors de l'envoi du formulaire." : "Oops! Something went wrong while submitting the form."}</div>
            </div>
          )}
        </Block>
      )}
    </Block>
  );
}

/**
 * Props for {@link Footer}
 */
export type FooterProps = {};

/**
 * Footer
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Locales Wrapper`, `Collection List`
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function Footer({}: FooterProps) {
  const [blogPosts, setBlogPosts] = useState<any[]>([]);
  const [newsItems, setNewsItems] = useState<any[]>([]);

  useEffect(() => {
    getBlogPosts("en", 4)
      .then((data) => setBlogPosts(data || []))
      .catch(() => {});
    getNews("en", 4)
      .then((data) => setNewsItems(data || []))
      .catch(() => {});
  }, []);

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"footer"}
        grid={{
          type: "section",
        }}
        id={"w-node-e77519be-32ac-35f9-e6e2-a8620379ed03-0379ed03"}
        tag={"footer"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"None"} />
          <Block className={"container-84rem"} tag={"div"}>
            <FooterNewsletter />
          </Block>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"footer_component"} tag={"div"}>
              <Block className={"footer_brand"} tag={"div"}>
                <Link
                  block={"inline"}
                  button={false}
                  className={"footer_linkblock"}
                  options={{
                    href: "/en/",
                  }}
                >
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                    }
                    width={"120"}
                  />
                </Link>
                <Block className={"spacer-1rem"} tag={"div"}>
                  <Block className={"spacer-0x25rem"} tag={"div"} />
                </Block>
                <Paragraph className={"heading-size-1x375rem"}>
                  {"Your CSR and"}
                  <br />
                  {"compliance copilot"}
                </Paragraph>
                <Block className={"spacer-2rem"} tag={"div"} />
                <ElementSocialproofTrustpilot />
                <Block className={"spacer-2rem"} tag={"div"} />
                <Block className={"footer_socials_list"} tag={"div"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"socials_link"}
                    options={{
                      href: "https://www.linkedin.com/company/trustditto/",
                      target: "_blank",
                    }}
                  >
                    <HtmlEmbed
                      className={"icon"}
                      content={
                        '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_305_5063)">\n<path d="M18.5195 0H1.47656C0.660156 0 0 0.644531 0 1.44141V18.5547C0 19.3516 0.660156 20 1.47656 20H18.5195C19.3359 20 20 19.3516 20 18.5586V1.44141C20 0.644531 19.3359 0 18.5195 0ZM5.93359 17.043H2.96484V7.49609H5.93359V17.043ZM4.44922 6.19531C3.49609 6.19531 2.72656 5.42578 2.72656 4.47656C2.72656 3.52734 3.49609 2.75781 4.44922 2.75781C5.39844 2.75781 6.16797 3.52734 6.16797 4.47656C6.16797 5.42188 5.39844 6.19531 4.44922 6.19531ZM17.043 17.043H14.0781V12.4023C14.0781 11.2969 14.0586 9.87109 12.5352 9.87109C10.9922 9.87109 10.7578 11.0781 10.7578 12.3242V17.043H7.79688V7.49609H10.6406V8.80078H10.6797C11.0742 8.05078 12.043 7.25781 13.4844 7.25781C16.4883 7.25781 17.043 9.23438 17.043 11.8047V17.043Z" fill="#130E30"/>\n</g>\n<defs>\n<clipPath id="clip0_305_5063">\n<rect width="20" height="20" fill="white"/>\n</clipPath>\n</defs>\n</svg>'
                      }
                    />
                  </Link>
                  <Block className={"w-locales-list"} tag={"div"}>
                    <Block className={"w-locales-items"} tag={"div"} role={"list"}>
                      <Block className={"w-locales-item"} tag={"div"} role={"listitem"}>
                        <Link block={""} button={false} options={{ href: "/en/" }}>
                          {"English"}
                        </Link>
                      </Block>
                      <Block className={"w-locales-item"} tag={"div"} role={"listitem"}>
                        <Link block={""} button={false} options={{ href: "/fr/" }}>
                          {"Français"}
                        </Link>
                      </Block>
                    </Block>
                  </Block>
                </Block>
                <Block className={"spacer-2rem"} tag={"div"} />
                <Block className={"footer_legal_list"} tag={"div"}>
                  <Paragraph className={"text-size-0x875rem text-weight-600"}>
                    {"© 2025 Ditto."}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"text-size-0x875rem"}
                    options={{
                      href: "/en/legal/terms-and-conditions",
                    }}
                  >
                    {"Terms"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"text-size-0x875rem"}
                    options={{
                      href: "/en/legal/privacy-policy",
                    }}
                  >
                    {"Privacy"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"text-size-0x875rem"}
                    options={{
                      href: "/en/legal/legal-notices",
                    }}
                  >
                    {"Legal notices"}
                  </Link>
                </Block>
              </Block>
              <Block className={"footer_navigation"} tag={"nav"}>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"Frameworks"}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/frameworks/ecovadis",
                    }}
                  >
                    {"Ecovadis"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/frameworks/cdp",
                    }}
                  >
                    {"CDP"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/frameworks/csrd",
                    }}
                  >
                    {"CSRD"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/frameworks/iso-14001",
                    }}
                  >
                    {"ISO 14001"}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"Solutions"}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/solutions/management-system",
                    }}
                  >
                    {"Management System"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/solutions/compliance-questionnaires",
                    }}
                  >
                    {"Compliance questionnaire"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/solutions/ai-solutions",
                    }}
                  >
                    {"Artificial Intelligence"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/solutions/supplier-engagement",
                    }}
                  >
                    {"Supplier Engagement"}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"Customers"}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/customer-stories?team-size_equal=100-250",
                    }}
                  >
                    {"SME"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/customer-stories?team-size_equal=1000-5000",
                    }}
                  >
                    {"Large Companies"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/customer-stories",
                    }}
                  >
                    {"All Case Studies"}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"Resources"}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/resources",
                    }}
                  >
                    {"All"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/resources/blog",
                    }}
                  >
                    {"Blog"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/resources/news",
                    }}
                  >
                    {"News"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/resources/guides",
                    }}
                  >
                    {"Guides"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "https://app.livestorm.co/trustditto?lang=en",
                      target: "_blank",
                    }}
                  >
                    {"Events"}
                  </Link>
                </Block>
                <Block className={"footer_navigation_col"} tag={"div"}>
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"About Us"}
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"link-size-1rem"}
                    options={{
                      href: "/en/manifesto",
                    }}
                  >
                    {"Manifesto"}
                  </Link>
                  <DOM
                    className={"link-size-1rem obflink"}
                    data-o={
                      "aHR0cHM6Ly93d3cudHJ1c3RkaXR0by5jb20vZW4vY2FyZWVycw=="
                    }
                    tag={"span"}
                  >
                    {"Careers"}
                  </DOM>
                </Block>
                <Block
                  className={"footer_navigation_col width-20rem"}
                  tag={"div"}
                >
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"Blog"}
                  </Paragraph>
                  {blogPosts.map((post) => (
                    <Link
                      key={post.id}
                      block={""}
                      button={false}
                      className={"link-size-1rem"}
                      options={{ href: `/en/resources/blog/${post.slug}` }}
                    >
                      {post.name}
                    </Link>
                  ))}
                </Block>
                <Block
                  className={"footer_navigation_col width-20rem"}
                  tag={"div"}
                >
                  <Paragraph className={"text-size-1rem text-weight-600"}>
                    {"News"}
                  </Paragraph>
                  {newsItems.map((item) => (
                    <Link
                      key={item.id}
                      block={""}
                      button={false}
                      className={"link-size-1rem"}
                      options={{ href: `/en/resources/news/${item.slug}` }}
                    >
                      {item.name}
                    </Link>
                  ))}
                </Block>
              </Block>
            </Block>
          </Block>
          <Padding space={"Small (3rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
