/**
 * @generated
 * @file Navbar (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { useTranslations, useLocale } from "next-intl";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { getBlogPosts, getCustomerStories } from "../lib/cms";
import { localizedHref, localizedCmsHref, switchLocalePath, collectionPath } from "../lib/localized-paths";
import { CUSTOMER_INDUSTRIES, industryName } from "../lib/customer-industries";
import { MegaNav, type MegaMenu } from "./MegaNav";
import { useAlternateUrls } from "./AlternateUrlContext";
import { DEVLINK_SCOPE_CLASS } from "../../devlink/devlinkScope";
import Block from "../../devlink/modules/Basic/components/Block";
import DropdownList from "../../devlink/modules/Dropdown/components/DropdownList";
import DropdownToggle from "../../devlink/modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "../../devlink/modules/Dropdown/components/DropdownWrapper";
import HtmlEmbed from "../../devlink/modules/Embed/components/HtmlEmbed";
import Image from "../../devlink/modules/Basic/components/Image";
import Link from "../../devlink/modules/Basic/components/Link";
import NavbarBrand from "../../devlink/modules/Navbar/components/NavbarBrand";
import NavbarButton from "../../devlink/modules/Navbar/components/NavbarButton";
import NavbarContainer from "../../devlink/modules/Navbar/components/NavbarContainer";
import NavbarLink from "../../devlink/modules/Navbar/components/NavbarLink";
import NavbarMenu from "../../devlink/modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "../../devlink/modules/Navbar/components/NavbarWrapper";
import Paragraph from "../../devlink/modules/Basic/components/Paragraph";
import { Button } from "../../devlink/elements/Button";

/**
 * Props for {@link Navbar}
 */
export type NavbarProps = {
  previewPosts?: any[];
  customerStories?: any[];
  alternateUrls?: Record<string, string>;
};

/**
 * Navbar
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Collection List`, `Locales Wrapper`
 *
 */
export function NavbarClient({
  previewPosts: serverPosts,
  customerStories: serverStories,
  alternateUrls,
}: NavbarProps) {
  const t = useTranslations("nav");
  const locale = useLocale();
  const pathname = usePathname();
  const { urls: contextUrls } = useAlternateUrls();
  const resolvedAlternateUrls = alternateUrls || contextUrls;
  const p = `/${locale}`;
  const [clientPosts, setClientPosts] = useState<any[]>(serverPosts || []);
  const [clientStories, setClientStories] = useState<any[]>(serverStories || []);

  useEffect(() => {
    if (serverPosts) return;
    getBlogPosts(locale as "en" | "fr", 2)
      .then((data) => setClientPosts(data || []))
      .catch(() => {});
  }, [locale, serverPosts]);

  useEffect(() => {
    if (serverStories) return;
    getCustomerStories(locale as "en" | "fr")
      .then((data) => setClientStories((data || []).slice(0, 5)))
      .catch(() => {});
  }, [locale, serverStories]);

  const previewPosts = serverPosts || clientPosts;
  const customerStories = serverStories || clientStories;

  // Webinars are hosted externally on Livestorm; keep the locale-aware link.
  const webinarsHref =
    locale === "fr"
      ? "https://app.livestorm.co/trustditto?lang=fr"
      : "https://app.livestorm.co/trustditto?lang=en";

  // Lucide icon key per industry (rendered as a yellow chip in Solution).
  const INDUSTRY_ICONS: Record<string, string> = {
    "aerospace-defense": "plane",
    construction: "hard-hat",
    electronics: "cpu",
    "manufacturing-equipment": "factory",
    retail: "shopping-bag",
    "technology-software": "monitor",
    "transportation-logistics": "truck",
  };
  const industryLinks = [...CUSTOMER_INDUSTRIES]
    .map((industry) => ({
      label: industryName(industry, locale),
      href: localizedHref(`/industry/${industry.slug}`, locale),
      icon: INDUSTRY_ICONS[industry.slug],
    }))
    .sort((a, b) => a.label.localeCompare(b.label, locale));

  // Single source of truth for the megamenus (Level 1 > Level 2 group > Level 3).
  const megaMenus: MegaMenu[] = [
    {
      id: "product",
      label: t("product"),
      featured: {
        kind: "promo",
        promo: {
          eyebrow: t("deadlineWatch"),
          title: t("deadlineTitle"),
          ctaLabel: t("startEarly"),
          ctaHref: localizedHref("/frameworks/cdp", locale),
        },
      },
      groups: [
        {
          id: "byFramework",
          heading: t("byFramework"),
          links: [
            { label: t("ecovadis"), href: localizedHref("/frameworks/ecovadis", locale) },
            { label: t("cdp"), href: localizedHref("/frameworks/cdp", locale) },
            { label: t("csrd"), href: localizedHref("/frameworks/csrd", locale) },
            { label: t("carbon"), href: localizedHref("/frameworks/carbon", locale) },
            { label: t("iso14001"), href: localizedHref("/frameworks/iso-14001", locale) },
          ],
        },
        {
          id: "byFeature",
          heading: t("byFeatures"),
          links: [
            { label: t("managementSystem"), href: localizedHref("/solutions/management-system", locale) },
            { label: t("complianceQuestionnaires"), href: localizedHref("/solutions/compliance-questionnaires", locale) },
            { label: t("aiSolutions"), href: localizedHref("/solutions/ai-solutions", locale) },
            { label: t("supplierEngagement"), href: localizedHref("/solutions/supplier-engagement", locale) },
          ],
        },
      ],
    },
    {
      id: "solution",
      label: t("solution"),
      groups: [
        {
          id: "byIndustry",
          heading: t("byIndustry"),
          columns: 2,
          variant: "icon",
          links: industryLinks,
        },
        // Future: "By size" group — deferred.
      ],
    },
    {
      id: "resources",
      label: t("resources"),
      featured: { kind: "article", title: t("featuredReading") },
      groups: [
        {
          id: "customerStories",
          heading: t("customerStories"),
          links: [
            ...customerStories.slice(0, 5).map((story: any) => ({
              // Show the company name (entreprise), not the long article title.
              label: ((story.entreprise && story.entreprise.trim()) || story.name) as string,
              href: localizedCmsHref("/customer-stories", story.slug, story.slug_fr, locale),
            })),
            { label: t("allStories"), href: localizedHref("/customer-stories", locale) },
          ],
        },
        {
          id: "perTopic",
          heading: t("perTopic"),
          links: [
            { label: t("ecovadis"), href: collectionPath("ecovadis", locale) },
            { label: t("cdp"), href: collectionPath("cdp", locale) },
            { label: "CSRD", href: collectionPath("csrd", locale) },
            { label: "VSME", href: collectionPath("vsme", locale) },
            { label: t("carbon"), href: collectionPath("carbon", locale) },
            { label: t("iso14001"), href: collectionPath("iso-14001", locale) },
            { label: "QHSE", href: collectionPath("qhse", locale) },
          ],
        },
        {
          id: "learn",
          heading: t("learn"),
          links: [
            { label: t("blog"), href: localizedHref("/resources/blog", locale) },
            { label: t("guides"), href: localizedHref("/resources/guides", locale) },
            { label: t("webinars"), href: webinarsHref, target: "_blank" },
            { label: t("news"), href: localizedHref("/resources/news", locale) },
          ],
        },
      ],
    },
  ];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NavbarWrapper
        className={"navbar1"}
        config={{
          easing: "ease",
          easing2: "ease",
          duration: 400,
          docHeight: false,
          noScroll: false,
          animation: "default",
          collapse: "medium",
        }}
        tag={"div"}
      >
        <NavbarContainer className={"navbar_container"} tag={"div"}>
          <Block className={"spacer-1rem"} tag={"div"} />
          <Block className={"navbar1_component container-80rem"} tag={"div"}>
            <NavbarBrand
              className={"navbar_mobile-brand"}
              options={{
                href: `${p}/`,
              }}
            >
              <Image
                alt={""}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                }
                width={"120"}
              />
            </NavbarBrand>
            <NavbarMenu
              className={"navbar1_menu"}
              role={"navigation"}
              tag={"nav"}
            >
              <Link
                block={"inline"}
                button={false}
                className={"navbar_brand"}
                options={{
                  href: `${p}/`,
                }}
              >
                <Image
                  alt={""}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                  }
                  width={"120"}
                />
              </Link>
              <Block className={"navbar1_navigation-list"} tag={"div"}>
                <MegaNav menus={megaMenus} previewPosts={previewPosts} locale={locale} />
                <NavbarLink
                  className={"navbar1_link"}
                  options={{ href: localizedHref("/plans", locale) }}
                >
                  {t("plans")}
                </NavbarLink>
                <DropdownWrapper
                  className={"navbar_language-dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle
                    className={"navbar_language-dropdown-button"}
                    tag={"div"}
                  >
                    <Block className={"icon-wrapper"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_2319_5414)">\n<path d="M10 19.375C15.1777 19.375 19.375 15.1777 19.375 10C19.375 4.82233 15.1777 0.625 10 0.625C4.82233 0.625 0.625 4.82233 0.625 10C0.625 15.1777 4.82233 19.375 10 19.375Z" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M7.74083 19.1008C6.4725 17.2408 5.625 13.8608 5.625 10C5.625 6.13917 6.4725 2.75917 7.74083 0.89917" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M0.625 10H19.375" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M2.06836 15H17.9317" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M2.06836 5H17.9317" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M12.2588 0.89917C13.5271 2.75917 14.3746 6.13917 14.3746 10C14.3746 13.8608 13.5271 17.2408 12.2588 19.1008" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_2319_5414">\n<rect width="20" height="20" fill="white"/>\n</clipPath>\n</defs>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdow2"} tag={"nav"}>
                    <Block className={"dropdown width-15rem"} tag={"div"}>
                      <Block className={"dropdown1_grid"} tag={"div"}>
                        <Block className={"dropdown_list1"} tag={"div"}>
                          <Block className={"dropdown_lang_wrapper"} tag={"div"}>
                            <Block className={"navbar_dropdown-language-links-list"} tag={"div"}>
                              <Block className={"navbar_dropdown-card-link"} tag={"div"}>
                                <Link block={""} button={false} className={"dropdown_lang_link"} options={{ href: resolvedAlternateUrls["en"] || switchLocalePath(pathname, "en") }}>
                                  {""}
                                </Link>
                                <Image alt={""} className={"dropdown_lang_flag"} loading={"lazy"} src={"/images/lang-en.svg"} />
                                <Paragraph className={"text-weight-600"}>{"English"}</Paragraph>
                              </Block>
                              <Block className={"navbar_dropdown-card-link"} tag={"div"}>
                                <Link block={""} button={false} className={"dropdown_lang_link"} options={{ href: resolvedAlternateUrls["fr"] || switchLocalePath(pathname, "fr") }}>
                                  {""}
                                </Link>
                                <Image alt={""} className={"dropdown_lang_flag"} loading={"lazy"} src={"/images/lang-fr.svg"} />
                                <Paragraph className={"text-weight-600"}>{"Français"}</Paragraph>
                              </Block>
                            </Block>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
              </Block>
              <Block className={"navbar_button-group"} tag={"div"}>
                <Block className={"navbar_button navbar_button--login"} tag={"div"}>
                  <Button
                    arrow={false}
                    link={{ href: "https://esg.trustditto.com/", target: "_blank" }}
                    text={t("login")}
                    variant={"Secondary"}
                  />
                </Block>
                <Block className={"navbar_button"} tag={"div"}>
                  <div data-cta-placement="navbar">
                    <Button
                      arrow={false}
                      link={{ href: localizedHref("/demo", locale) }}
                      text={t("getStarted")}
                    />
                  </div>
                </Block>
              </Block>
            </NavbarMenu>
            <Block className={"navbar1_mobile_button"} tag={"div"}>
              <div data-cta-placement="navbar">
                <Button
                  arrow={false}
                  link={{ href: localizedHref("/demo", locale) }}
                  text={t("getStarted")}
                  variant={"Primary - Small"}
                />
              </div>
            </Block>
            <NavbarButton className={"navbar1_menu-button"} tag={"div"}>
              <Block className={"navbar_hamburger"} tag={"div"}>
                <Block className={"navbar_hamburger-line"} tag={"div"} />
                <HtmlEmbed
                  className={"nav_hamburger-embed"}
                  content={
                    "<style>\n.navbar_hamburger {\n\t--thickness: 0.15rem;\n\t--gap: 0.5rem;\n\t--rotate: 45;\n  --width: 70%;\n}\n.w--open .navbar_hamburger-line {\n\twidth: 70% !important;\n\ttransform: scaleX(0);\n}\n.w--open .navbar_hamburger-line:first-child {\n\ttransform: translateY(calc(var(--thickness) + var(--gap))) rotate(calc(var(--rotate) * 3 * 1deg));\n}\n.w--open .navbar_hamburger-line:last-child {\n\ttransform: translateY(calc(var(--thickness) * -1 + var(--gap) * -1)) rotate(calc(var(--rotate) * 1deg));\n}\n</style>"
                  }
                />
                <Block className={"navbar_hamburger-line"} tag={"div"} />
                <Block className={"navbar_hamburger-line"} tag={"div"} />
              </Block>
            </NavbarButton>
          </Block>
          <Block className={"spacer-1rem"} tag={"div"} />
        </NavbarContainer>
        <HtmlEmbed
          className={"paste-to-global"}
          content={
            '<style>\n.navbar1_dropdown .icon-wrapper{\n\ttransition: transform 0.4s ease;\n}\n.navbar1_dropdown:hover .icon-wrapper, .navbar1_dropdown:has(.navbar1_link.w--open) .icon-wrapper{\n\ttransform: rotate(-180deg);\n}\n@media screen and (min-width: 992px){\n  .navbar1_dropdown:hover .navbar1_link.w--open{\n    background-color: var(--_colors-•-semantic---surface-tertiary);\n  }\n}\n</style>'
          }
        />
      </NavbarWrapper>
    </div>
  );
}
