/**
 * @generated
 * @file Navbar (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { useTranslations, useLocale } from "next-intl";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { getBlogPosts } from "../lib/cms";
import { localizedHref, localizedCmsHref, switchLocalePath } from "../lib/localized-paths";
import { useAlternateUrls } from "./AlternateUrlContext";
import { DEVLINK_SCOPE_CLASS } from "../../devlink/devlinkScope";
import Block from "../../devlink/modules/Basic/components/Block";
import DOM from "../../devlink/modules/Builtin/components/DOM";
import DropdownList from "../../devlink/modules/Dropdown/components/DropdownList";
import DropdownToggle from "../../devlink/modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "../../devlink/modules/Dropdown/components/DropdownWrapper";
import HtmlEmbed from "../../devlink/modules/Embed/components/HtmlEmbed";
import Image from "../../devlink/modules/Basic/components/Image";
import Link from "../../devlink/modules/Basic/components/Link";
import NavbarBrand from "../../devlink/modules/Navbar/components/NavbarBrand";
import NavbarButton from "../../devlink/modules/Navbar/components/NavbarButton";
import NavbarContainer from "../../devlink/modules/Navbar/components/NavbarContainer";
import NavbarLink from "../../devlink/modules/Navbar/components/NavbarLink";
import NavbarMenu from "../../devlink/modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "../../devlink/modules/Navbar/components/NavbarWrapper";
import Paragraph from "../../devlink/modules/Basic/components/Paragraph";
import { Button } from "../../devlink/elements/Button";
import { Label } from "../../devlink/elements/Label";

/**
 * Props for {@link Navbar}
 */
export type NavbarProps = {
  previewPosts?: any[];
  alternateUrls?: Record<string, string>;
};

/**
 * Navbar
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported elements: `Collection List`, `Locales Wrapper`
 *
 */
export function NavbarClient({ previewPosts: serverPosts, alternateUrls }: NavbarProps) {
  const t = useTranslations("nav");
  const locale = useLocale();
  const pathname = usePathname();
  const { urls: contextUrls } = useAlternateUrls();
  const resolvedAlternateUrls = alternateUrls || contextUrls;
  const p = `/${locale}`;
  const [clientPosts, setClientPosts] = useState<any[]>(serverPosts || []);

  useEffect(() => {
    if (serverPosts) return;
    getBlogPosts(locale as "en" | "fr", 2)
      .then((data) => setClientPosts(data || []))
      .catch(() => {});
  }, [locale, serverPosts]);

  const previewPosts = serverPosts || clientPosts;

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NavbarWrapper
        className={"navbar1"}
        config={{
          easing: "ease",
          easing2: "ease",
          duration: 400,
          docHeight: false,
          noScroll: false,
          animation: "default",
          collapse: "medium",
        }}
        tag={"div"}
      >
        <NavbarContainer className={"navbar_container"} tag={"div"}>
          <Block className={"spacer-1rem"} tag={"div"} />
          <Block className={"navbar1_component container-80rem"} tag={"div"}>
            <NavbarBrand
              className={"navbar_mobile-brand"}
              options={{
                href: `${p}/`,
              }}
            >
              <Image
                alt={""}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                }
                width={"120"}
              />
            </NavbarBrand>
            <NavbarMenu
              className={"navbar1_menu"}
              role={"navigation"}
              tag={"nav"}
            >
              <Link
                block={"inline"}
                button={false}
                className={"navbar_brand"}
                options={{
                  href: `${p}/`,
                }}
              >
                <Image
                  alt={""}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682d8b77e73e672cfd2353a9_ditto-logo.svg"
                  }
                  width={"120"}
                />
              </Link>
              <Block className={"navbar1_navigation-list"} tag={"div"}>
                <DropdownWrapper
                  className={"navbar1_dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle className={"navbar1_link"} tag={"div"}>
                    <Block tag={"div"}>{t("frameworks")}</Block>
                    <Block className={"icon-wrapper is-16px"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M3.5312 5.52729C3.79155 5.26694 4.21366 5.26694 4.47401 5.52729L8.0026 9.05589L11.5312 5.52729C11.7915 5.26694 12.2137 5.26694 12.474 5.52729C12.7344 5.78764 12.7344 6.20975 12.474 6.4701L8.47401 10.4701C8.21366 10.7305 7.79155 10.7305 7.5312 10.4701L3.5312 6.4701C3.27085 6.20975 3.27085 5.78764 3.5312 5.52729Z" fill="#130E30"/>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList
                    className={"navbar1_dropdown-small"}
                    tag={"nav"}
                  >
                    <Block className={"dropdown"} tag={"div"}>
                      <Block className={"dropdown1_grid"} tag={"div"}>
                        <Block className={"dropdown_list1"} tag={"div"}>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: `${p}/frameworks/ecovadis`,
                              }}
                            >
                              {t("ecovadis")}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {t("descEcovadis")}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: `${p}/frameworks/iso-14001`,
                              }}
                            >
                              {t("iso14001")}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {t("descIso14001")}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: `${p}/frameworks/cdp`,
                              }}
                            >
                              {t("cdp")}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {t("descCdp")}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: `${p}/frameworks/csrd`,
                              }}
                            >
                              {t("csrd")}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {t("descCsrd")}
                            </Paragraph>
                          </Block>
                          <Block className={"dropdown_list1_card"} tag={"div"}>
                            <Link
                              block={""}
                              button={false}
                              className={
                                "text-size-1rem text-weight-600 link-hover-parent"
                              }
                              options={{
                                href: `${p}/frameworks`,
                              }}
                            >
                              {t("otherFrameworks")}
                            </Link>
                            <Paragraph
                              className={
                                "text-size-0x875rem text-color-neutral hide-tablet"
                              }
                            >
                              {
                                t("descOtherFrameworks")
                              }
                            </Paragraph>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
                <DropdownWrapper
                  className={"navbar1_dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle className={"navbar1_link"} tag={"div"}>
                    <Block tag={"div"}>{t("solutions")}</Block>
                    <Block className={"icon-wrapper is-16px"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M8.50001 8.78145L11.8 5.48145L12.7427 6.42411L8.50001 10.6668L4.25734 6.42411L5.20001 5.48145L8.50001 8.78145Z" fill="#171B26"/>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdow2"} tag={"nav"}>
                    <Block className={"dropdown2_wrapper"} tag={"div"}>
                      <Block className={"dropdown"} tag={"div"}>
                        <Block className={"dropdown1_grid"} tag={"div"}>
                          <Block className={"dropdown_list1"} tag={"div"}>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: `${p}/solutions/management-system`,
                                }}
                              >
                                {t("managementSystem")}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {t("descManagementSystem")}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: `${p}/solutions/compliance-questionnaires`,
                                }}
                              >
                                {t("complianceQuestionnaires")}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {t("descComplianceQuestionnaires")}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: `${p}/solutions/ai-solutions`,
                                }}
                              >
                                {t("aiSolutions")}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {t("descAiSolutions")}
                              </Paragraph>
                            </Block>
                            <Block
                              className={"dropdown_list1_card"}
                              tag={"div"}
                            >
                              <Link
                                block={""}
                                button={false}
                                className={
                                  "text-size-1rem text-weight-600 link-hover-parent"
                                }
                                options={{
                                  href: `${p}/solutions/supplier-engagement`,
                                }}
                              >
                                {t("supplierEngagement")}
                              </Link>
                              <Paragraph
                                className={
                                  "text-size-0x875rem text-color-neutral hide-tablet"
                                }
                              >
                                {t("descSupplierEngagement")}
                              </Paragraph>
                            </Block>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
                <ResourcesMegaMenu previewPosts={previewPosts} />
                <NavbarLink
                  className={"navbar1_link"}
                  options={{ href: localizedHref("/plans", locale) }}
                >
                  {t("plans")}
                </NavbarLink>
                <DropdownWrapper
                  className={"navbar_language-dropdown"}
                  delay={0}
                  hover={true}
                  tag={"div"}
                >
                  <DropdownToggle
                    className={"navbar_language-dropdown-button"}
                    tag={"div"}
                  >
                    <Block className={"icon-wrapper"} tag={"div"}>
                      <HtmlEmbed
                        className={"icon"}
                        content={
                          '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_2319_5414)">\n<path d="M10 19.375C15.1777 19.375 19.375 15.1777 19.375 10C19.375 4.82233 15.1777 0.625 10 0.625C4.82233 0.625 0.625 4.82233 0.625 10C0.625 15.1777 4.82233 19.375 10 19.375Z" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M7.74083 19.1008C6.4725 17.2408 5.625 13.8608 5.625 10C5.625 6.13917 6.4725 2.75917 7.74083 0.89917" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M0.625 10H19.375" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M2.06836 15H17.9317" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M2.06836 5H17.9317" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M12.2588 0.89917C13.5271 2.75917 14.3746 6.13917 14.3746 10C14.3746 13.8608 13.5271 17.2408 12.2588 19.1008" stroke="black" stroke-width="1.25" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_2319_5414">\n<rect width="20" height="20" fill="white"/>\n</clipPath>\n</defs>\n</svg>'
                        }
                      />
                    </Block>
                  </DropdownToggle>
                  <DropdownList className={"navbar1_dropdow2"} tag={"nav"}>
                    <Block className={"dropdown width-15rem"} tag={"div"}>
                      <Block className={"dropdown1_grid"} tag={"div"}>
                        <Block className={"dropdown_list1"} tag={"div"}>
                          <Block className={"dropdown_lang_wrapper"} tag={"div"}>
                            <Block className={"navbar_dropdown-language-links-list"} tag={"div"}>
                              <Block className={"navbar_dropdown-card-link"} tag={"div"}>
                                <Link block={""} button={false} className={"dropdown_lang_link"} options={{ href: resolvedAlternateUrls["en"] || switchLocalePath(pathname, "en") }}>
                                  {""}
                                </Link>
                                <Image alt={""} className={"dropdown_lang_flag"} loading={"lazy"} src={"/images/lang-en.svg"} />
                                <Paragraph className={"text-weight-600"}>{"English"}</Paragraph>
                              </Block>
                              <Block className={"navbar_dropdown-card-link"} tag={"div"}>
                                <Link block={""} button={false} className={"dropdown_lang_link"} options={{ href: resolvedAlternateUrls["fr"] || switchLocalePath(pathname, "fr") }}>
                                  {""}
                                </Link>
                                <Image alt={""} className={"dropdown_lang_flag"} loading={"lazy"} src={"/images/lang-fr.svg"} />
                                <Paragraph className={"text-weight-600"}>{"Français"}</Paragraph>
                              </Block>
                            </Block>
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </DropdownList>
                </DropdownWrapper>
              </Block>
              <Block className={"navbar_button-group"} tag={"div"}>
                <Block className={"navbar_button navbar_button--login"} tag={"div"}>
                  <Button
                    arrow={false}
                    link={{ href: "https://esg.trustditto.com/", target: "_blank" }}
                    text={t("login")}
                    variant={"Secondary"}
                  />
                </Block>
                <Block className={"navbar_button"} tag={"div"}>
                  <div data-cta-placement="navbar">
                    <Button
                      arrow={false}
                      link={{ href: localizedHref("/demo", locale) }}
                      text={t("getStarted")}
                    />
                  </div>
                </Block>
              </Block>
            </NavbarMenu>
            <Block className={"navbar1_mobile_button"} tag={"div"}>
              <div data-cta-placement="navbar">
                <Button
                  arrow={false}
                  link={{ href: localizedHref("/demo", locale) }}
                  text={t("getStarted")}
                  variant={"Primary - Small"}
                />
              </div>
            </Block>
            <NavbarButton className={"navbar1_menu-button"} tag={"div"}>
              <Block className={"navbar_hamburger"} tag={"div"}>
                <Block className={"navbar_hamburger-line"} tag={"div"} />
                <HtmlEmbed
                  className={"nav_hamburger-embed"}
                  content={
                    "<style>\n.navbar_hamburger {\n\t--thickness: 0.15rem;\n\t--gap: 0.5rem;\n\t--rotate: 45;\n  --width: 70%;\n}\n.w--open .navbar_hamburger-line {\n\twidth: 70% !important;\n\ttransform: scaleX(0);\n}\n.w--open .navbar_hamburger-line:first-child {\n\ttransform: translateY(calc(var(--thickness) + var(--gap))) rotate(calc(var(--rotate) * 3 * 1deg));\n}\n.w--open .navbar_hamburger-line:last-child {\n\ttransform: translateY(calc(var(--thickness) * -1 + var(--gap) * -1)) rotate(calc(var(--rotate) * 1deg));\n}\n</style>"
                  }
                />
                <Block className={"navbar_hamburger-line"} tag={"div"} />
                <Block className={"navbar_hamburger-line"} tag={"div"} />
              </Block>
            </NavbarButton>
          </Block>
          <Block className={"spacer-1rem"} tag={"div"} />
        </NavbarContainer>
        <HtmlEmbed
          className={"paste-to-global"}
          content={
            '<style>\n.navbar1_dropdown .icon-wrapper{\n\ttransition: transform 0.4s ease;\n}\n.navbar1_dropdown:hover .icon-wrapper, .navbar1_dropdown:has(.navbar1_link.w--open) .icon-wrapper{\n\ttransform: rotate(-180deg);\n}\n@media screen and (min-width: 992px){\n  .navbar1_dropdown:hover .navbar1_link.w--open{\n    background-color: var(--_colors-•-semantic---surface-tertiary);\n  }\n  \n  .dropdown1_grid{\n    grid-template-columns: 23.5rem 0rem;\n    transition-property: grid-template-columns;\n    transition-delay: 400ms;\n    transition-duration: 400ms;\n    transition-timing-function: ease-in-out;\n  }\n\n  .navbar1_dropdown-small{\n    left: 0rem;\n  }\n\n  .dropdown1_grid:has([dropdown-accordion="csrd-link"]:hover), .dropdown1_grid:has(.dropdown1_grid_clip:hover) {\n    grid-template-columns: 23.5rem 27rem;\n    transition-delay: 0ms;\n  }\n\n  .navbar1_dropdown-small:has([dropdown-accordion="csrd-link"]){\n    transition-property: left;\n    transition-delay: 400ms;\n    transition-duration: 400ms;\n    transition-timing-function: ease-in-out;\n    left: 0rem;\n  }\n\n  .navbar1_dropdown-small:has([dropdown-accordion="csrd-link"]:hover), .navbar1_dropdown-small:has(.dropdown1_grid_clip:hover){\n    left: -13.5rem;\n    transition-delay: 0ms;\n  }\n}\n\n\n\n\n\n</style>'
          }
        />
      </NavbarWrapper>
    </div>
  );
}

const CHEVRON_DOWN =
  '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M3.5312 5.52729C3.79155 5.26694 4.21366 5.26694 4.47401 5.52729L8.0026 9.05589L11.5312 5.52729C11.7915 5.26694 12.2137 5.26694 12.474 5.52729C12.7344 5.78764 12.7344 6.20975 12.474 6.4701L8.47401 10.4701C8.21366 10.7305 7.79155 10.7305 7.5312 10.4701L3.5312 6.4701C3.27085 6.20975 3.27085 5.78764 3.5312 5.52729Z" fill="#130E30"/>\n</svg>';

const ARROW_RIGHT =
  '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';

type MegaItem = {
  label: React.ReactNode;
  href: string;
  desc?: string;
  target?: "_blank" | "_self";
};

type MegaBucket = {
  id: string;
  label: string;
  items: MegaItem[];
  showPreview?: boolean;
};

/**
 * Vanta-style mega-menu for the "Resources" nav item. A left column of buckets
 * (Customers / Compliance resources / Company / All resources) swaps the
 * right-hand content panel on hover/focus. Replaces the former standalone
 * Customers link plus the Resources and About dropdowns.
 */
function ResourcesMegaMenu({ previewPosts }: { previewPosts: any[] }) {
  const t = useTranslations("nav");
  const locale = useLocale();
  const p = `/${locale}`;
  const csBase = localizedHref("/customer-stories", locale);
  const webinarsHref =
    locale === "fr"
      ? "https://app.livestorm.co/trustditto?lang=fr"
      : "https://app.livestorm.co/trustditto?lang=en";

  const buckets: MegaBucket[] = [
    {
      id: "allResources",
      label: t("bucketAllResources"),
      showPreview: true,
      items: [
        { label: t("allResources"), href: localizedHref("/resources", locale) },
        { label: t("blog"), href: localizedHref("/resources/blog", locale), desc: t("descBlog") },
        { label: t("guidesAndReports"), href: localizedHref("/resources/guides", locale), desc: t("descGuides") },
        { label: t("webinars"), href: webinarsHref, target: "_blank", desc: t("descWebinars") },
        { label: t("news"), href: localizedHref("/resources/news", locale), desc: t("descNews") },
      ],
    },
    {
      id: "customers",
      label: t("bucketCustomers"),
      items: [
        { label: t("allCustomerStories"), href: csBase },
        { label: t("industryBusinessServices"), href: `${csBase}?industry=business-services` },
        { label: t("industryConstructionMaterials"), href: `${csBase}?industry=construction-materials` },
        { label: t("industryCosmeticsBeauty"), href: `${csBase}?industry=cosmetics-beauty` },
        { label: t("industryDistributionWholesale"), href: `${csBase}?industry=distribution-wholesale` },
        { label: t("industryIndustrialEquipment"), href: `${csBase}?industry=industrial-equipment-systems` },
        { label: t("industryTransportationLogistics"), href: `${csBase}?industry=transportation-logistics` },
      ],
    },
    {
      id: "compliance",
      label: t("bucketComplianceResources"),
      items: [
        { label: t("ecovadis"), href: `${p}/collection/ecovadis`, desc: t("descCollectionEcovadis") },
        { label: t("cdp"), href: `${p}/collection/cdp`, desc: t("descCollectionCdp") },
        { label: "VSME", href: `${p}/collection/vsme`, desc: t("descCollectionVsme") },
      ],
    },
    {
      id: "company",
      label: t("bucketCompany"),
      items: [
        { label: t("manifesto"), href: `${p}/manifesto`, desc: t("descManifesto") },
        { label: t("careers"), href: `${p}/careers`, desc: t("descCareers") },
      ],
    },
  ];

  const [activeId, setActiveId] = useState(buckets[0].id);
  const active = buckets.find((b) => b.id === activeId) ?? buckets[0];

  return (
    <DropdownWrapper className={"navbar1_dropdown"} delay={0} hover={true} tag={"div"}>
      <DropdownToggle className={"navbar1_link"} tag={"div"}>
        <Block tag={"div"}>{t("resources")}</Block>
        <Block className={"icon-wrapper is-16px"} tag={"div"}>
          <HtmlEmbed className={"icon"} content={CHEVRON_DOWN} />
        </Block>
      </DropdownToggle>
      <DropdownList className={"navbar1_dropdown-big"} tag={"nav"}>
        <Block className={"dropdown-big_wrapper"} tag={"div"}>
          <Block className={"dropdown"} tag={"div"}>
            <div className={"resources-mega"}>
              <div className={"resources-mega_buckets"}>
                {buckets.map((b) => (
                  <button
                    key={b.id}
                    type={"button"}
                    className={`resources-mega_bucket${b.id === activeId ? " is-active" : ""}`}
                    onMouseEnter={() => setActiveId(b.id)}
                    onFocus={() => setActiveId(b.id)}
                    onClick={(e) => {
                      // Swap the right-hand submenu without letting the click
                      // bubble to Webflow's dropdown handler (which would close
                      // the whole menu) or trigger any navigation.
                      e.preventDefault();
                      e.stopPropagation();
                      setActiveId(b.id);
                    }}
                    aria-expanded={b.id === activeId}
                  >
                    <span>{b.label}</span>
                    <span
                      className={"resources-mega_bucket-arrow"}
                      dangerouslySetInnerHTML={{ __html: ARROW_RIGHT }}
                    />
                  </button>
                ))}
              </div>
              <div className={"resources-mega_panel"}>
                <div className={"resources-mega_links"}>
                  {active.items.map((item) => (
                    <Link
                      key={item.href}
                      block={""}
                      button={false}
                      className={"resources-mega_link link-hover-parent"}
                      options={{ href: item.href, ...(item.target ? { target: item.target } : {}) }}
                    >
                      <Block className={"text-size-1rem text-weight-600"} tag={"div"}>
                        {item.label}
                      </Block>
                      {item.desc ? (
                        <Paragraph className={"text-size-0x875rem text-color-neutral hide-tablet"}>
                          {item.desc}
                        </Paragraph>
                      ) : null}
                    </Link>
                  ))}
                </div>
                {active.showPreview && previewPosts.length > 0 ? (
                  <div className={"resources-mega_preview"}>
                    {previewPosts.map((post: any) => (
                      <Block key={post.slug} className={"dropdown1_card2"} tag={"div"}>
                        <Block className={"dropdown1_card2_content"} tag={"div"}>
                          <Paragraph className={"label"}>{"Blog"}</Paragraph>
                          <Block className={"spacer-0x5rem"} tag={"div"} />
                          <Link
                            block={""}
                            button={false}
                            className={"heading-size-1x375rem link-hover-parent text-style-2lines"}
                            options={{ href: localizedCmsHref("/resources/blog", post.slug, post.slug_fr, locale) }}
                          >
                            {post.name}
                          </Link>
                          <Block className={"spacer-0x5rem"} tag={"div"} />
                          <Paragraph className={"text-size-0x875rem text-style-3lines"}>
                            {post.description}
                          </Paragraph>
                        </Block>
                      </Block>
                    ))}
                  </div>
                ) : null}
              </div>
            </div>
          </Block>
        </Block>
      </DropdownList>
    </DropdownWrapper>
  );
}
