/**
 * @generated
 * @file SectionLogostrip (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { useEffect, useState } from "react";
import { useTranslations, useLocale } from "next-intl";
import { localizedHref } from "../lib/localized-paths";
import { getCompanyLogos, getCustomerStories } from "../lib/cms";
import { localizedCmsHref } from "../lib/localized-paths";
import { DEVLINK_SCOPE_CLASS } from "../../webflow/devlinkScope";
import Block from "../../webflow/webflow_modules/Basic/components/Block";
import Heading from "../../webflow/webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../../webflow/webflow_modules/Embed/components/HtmlEmbed";
import Image from "../../webflow/webflow_modules/Basic/components/Image";
import Link from "../../webflow/webflow_modules/Basic/components/Link";
import Paragraph from "../../webflow/webflow_modules/Basic/components/Paragraph";
import Section from "../../webflow/webflow_modules/Layout/components/Section";
import { Background } from "../../webflow/Background";
import { Padding } from "../../webflow/Padding";

/**
 * Props for {@link SectionLogostrip}
 */
export type SectionLogostripProps = {
  variant?: "Base" | "Not clickable";
};

/**
 * SectionLogostrip
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionLogostrip({ variant = "Base" }: SectionLogostripProps) {
  const t = useTranslations("socialProof");
  const locale = useLocale();
  const prefix = `/${locale}`;
  const [logos, setLogos] = useState<any[]>([]);
  const [storySlugMap, setStorySlugMap] = useState<Record<string, { slug: string; slug_fr: string | null }>>({});

  useEffect(() => {
    getCompanyLogos().then((data) => setLogos(data || []));
    // Build a map of English slug → { slug, slug_fr } from customer stories
    getCustomerStories(locale as "en" | "fr").then((stories) => {
      const map: Record<string, { slug: string; slug_fr: string | null }> = {};
      for (const s of stories || []) {
        map[s.slug] = { slug: s.slug, slug_fr: s.slug_fr };
      }
      setStorySlugMap(map);
    });
  }, [locale]);

  const _styleVariantMap = {
    Base: "",
    "Not clickable": "w-variant-4264a7db-e569-0907-b261-b783f2c8be66",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`logostrip_section ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        id={"w-node-fe04e33d-a26d-fee6-d70d-7145bfe0c248-bfe0c248"}
        tag={"section"}
      >
        <Block className={`padding-global ${_activeStyleVariant}`} tag={"div"}>
          <Padding space={"Small (3rem)"} />
          <Block
            className={`container-84rem ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block className={`header ${_activeStyleVariant}`} tag={"div"}>
              <Heading
                className={`text-size-1rem text-weight-400 ${_activeStyleVariant}`}
                tag={"h2"}
              >
                {t("title")}
              </Heading>
            </Block>
            <Block
              className={`spacer-2rem ${_activeStyleVariant}`}
              tag={"div"}
            />
            {logos.length > 0 ? (
              <Block className={"logostrip_list_wrapper w-dyn-list"} tag={"div"}>
                <Block
                  className={"logostrip_list w-dyn-items"}
                  tag={"div"}
                  role={"list"}
                >
                  {logos.map((logo) => (
                    <Block
                      key={logo.id}
                      className={"logostrip_item w-dyn-item"}
                      tag={"div"}
                      role={"listitem"}
                    >
                      {logo.case_study_url ? (() => {
                        // Extract the slug from the case_study_url (e.g. "/customer-stories/ferco-..." → "ferco-...")
                        const parts = logo.case_study_url.split("/");
                        const enSlug = parts[parts.length - 1];
                        const storyInfo = storySlugMap[enSlug];
                        const href = storyInfo
                          ? localizedCmsHref("/customer-stories", storyInfo.slug, storyInfo.slug_fr, locale)
                          : localizedHref(logo.case_study_url, locale);
                        return (
                        <Link
                          block={""}
                          button={false}
                          className={"logostrip_item_linkblock w-inline-block"}
                          options={{ href }}
                        >
                          <Block
                            className={"logostrip_item_image_wrapper"}
                            tag={"div"}
                          >
                            <Image
                              alt={logo.name || ""}
                              className={"logostrip_item_image"}
                              loading={"lazy"}
                              width={125}
                              src={logo.logo_url}
                            />
                          </Block>
                          <Block className={"button_tiny"} tag={"div"}>
                            <Block tag={"div"}>{t("caseStudy")}</Block>
                            <Block className={"icon-wrapper"} tag={"div"}>
                              <HtmlEmbed
                                tag={"div"}
                                className={"icon"}
                                value={`<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.14645 2.64645C4.34171 2.45118 4.65829 2.45118 4.85355 2.64645L7.85355 5.64645C8.04882 5.84171 8.04882 6.15829 7.85355 6.35355L4.85355 9.35355C4.65829 9.54882 4.34171 9.54882 4.14645 9.35355C3.95118 9.15829 3.95118 8.84171 4.14645 8.64645L6.79289 6L4.14645 3.35355C3.95118 3.15829 3.95118 2.84171 4.14645 2.64645Z" fill="currentColor"></path></svg>`}
                              />
                            </Block>
                          </Block>
                        </Link>
                        );
                      })() : (
                        <Block
                          className={"logostrip_item_image_wrapper"}
                          tag={"div"}
                        >
                          <Image
                            alt={logo.name || ""}
                            className={"logostrip_item_image"}
                            loading={"lazy"}
                            width={125}
                            src={logo.logo_url}
                          />
                        </Block>
                      )}
                    </Block>
                  ))}
                </Block>
              </Block>
            ) : null}
          </Block>
          <Padding space={"Small (3rem)"} />
        </Block>
        <Block className={`layer-4 ${_activeStyleVariant}`} tag={"div"}>
          <Background color={"Secondary"} />
        </Block>
      </Section>
    </div>
  );
}
