/**
 * @generated
 * @file SectionResources (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { useTranslations, useLocale } from "next-intl";
import { DEVLINK_SCOPE_CLASS } from "../../devlink/devlinkScope";
import Block from "../../devlink/modules/Basic/components/Block";
import Heading from "../../devlink/modules/Basic/components/Heading";
import Image from "../../devlink/modules/Basic/components/Image";
import Link from "../../devlink/modules/Basic/components/Link";
import Paragraph from "../../devlink/modules/Basic/components/Paragraph";
import Section from "../../devlink/modules/Layout/components/Section";
import { Background } from "../../devlink/Background";
import { Button } from "../../devlink/elements/Button";
import { Padding } from "../../devlink/Padding";
import { localizedCmsHref } from "../lib/localized-paths";
/**
 * Props for {@link SectionResources}
 */
export type SectionResourcesProps = {
  title?: React.ReactNode;
  serverPosts?: any[];
};

/**
 * SectionResources
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 */
export function SectionResources({
  title = "Learn more about Ditto & AI-powered CSR compliance",
  serverPosts = [],
}: SectionResourcesProps) {
  const t = useTranslations("resourcesSection");
  const locale = useLocale();
  const prefix = `/${locale}`;

  const posts = serverPosts;

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"blog-preview_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-f5af8294-c768-4701-7754-9613b683c062-b683c062"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Small (3rem)"} />
          <Block className={"container-48rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {title}
              </Heading>
            </Block>
          </Block>
          <Block className={"spacer-3rem"} tag={"div"} />
          <Block className={"container-84rem"} tag={"div"}>
            {posts.length > 0 ? (
              <div className="blog_list_wrapper w-dyn-list">
                <div role="list" className="blog_list w-dyn-items">
                  {posts.map((post) => (
                    <div key={post.id} role="listitem" className="blog-preview_item w-dyn-item">
                      <Block className="card-image" tag="div">
                        <Block className="card-image_thumbnail" tag="div">
                          <Image
                            className="media-full-size"
                            height="auto"
                            loading="lazy"
                            src={post.banner_url || ""}
                            width="auto"
                          />
                        </Block>
                        <Block className="card-image_content" tag="div">
                          <Block className="spacer-1x5rem spacer-mob-1rem" tag="div" />
                          <Paragraph className="label">
                            {post.category?.name_en || ""}
                          </Paragraph>
                          <Block className="spacer-0x75rem" tag="div" />
                          <Block className="card-image_link_wrapper" tag="div">
                            <Link
                              block=""
                              button={false}
                              className="heading-size-2rem link-hover-parent"
                              options={{ href: localizedCmsHref("/resources/blog", post.slug, post.slug_fr, locale) }}
                            >
                              {post.name}
                            </Link>
                          </Block>
                          <Block className="spacer-0x75rem" tag="div" />
                          <Paragraph className="text-size-1rem">
                            {post.description}
                          </Paragraph>
                        </Block>
                      </Block>
                    </div>
                  ))}
                </div>
              </div>
            ) : null}
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block className={"button-group x-center"} tag={"div"}>
              <Button
                arrow={false}
                link={{
                  href: `${prefix}/resources`,
                }}
                text={t("viewAll")}
                variant={"Secondary"}
              />
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
