/**
 * @generated
 * @file SectionContactSidebar (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { useTranslations, useLocale } from "next-intl";
import { useEffect, useRef } from "react";
import Script from "next/script";
import { DEVLINK_SCOPE_CLASS } from "../../webflow/devlinkScope";
import Block from "../../webflow/webflow_modules/Basic/components/Block";
import Heading from "../../webflow/webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../../webflow/webflow_modules/Embed/components/HtmlEmbed";
import Paragraph from "../../webflow/webflow_modules/Basic/components/Paragraph";
import Section from "../../webflow/webflow_modules/Layout/components/Section";
import { Background } from "../../webflow/Background";
import { Padding } from "../../webflow/Padding";

/**
 * Props for {@link SectionContactSidebar}
 */
const HUBSPOT_FORM_CSS = `
.hs-form fieldset { margin-bottom: 1.5rem; }
.hs-form-field { display: flex; flex-direction: column; gap: 8px; flex: 1; }
.form-columns-2 { display: flex; flex-wrap: wrap; gap: 24px; }
.form-columns-2 .hs-form-field { flex: 1 1 calc(50% - 12px); min-width: 260px; }
.form-columns-1 { display: flex; flex-direction: column; gap: 24px; }
.hs-form-field label { font-size: 16px; font-weight: 400; letter-spacing: -0.02em; color: #130E30; }
.hs-input { height: 48px; padding: 0 16px; background: #FFFFFF; border: none; border-radius: 6px; border-bottom: 1px solid #B6BA95; font-size: 16px; color: #130E30; box-sizing: border-box; width: 100%; }
.hs-input[type="textarea"], textarea.hs-input { height: 124px; padding: 14px 16px; resize: vertical; }
.hs-form-checkbox { display: flex; align-items: center; gap: 12px; margin-bottom: 0 !important; }
.hs-form-checkbox label { margin-bottom: 0 !important; }
.hs-form-checkbox-display input[type="checkbox"] { width: 20px; height: 20px; border: 1px solid #B6BA95; border-radius: 6px; margin-right: 8px; }
.hs-form-checkbox-display span { font-size: 16px; color: #130E30; }
.hs-button.primary { padding: 14px 24px; background: #130E30; color: #EFF2E5; border-radius: 999px; font-size: 16px; font-weight: 400; border: none; cursor: pointer; max-width: 200px; transition: background 0.3s ease; }
.hs-button.primary:hover { background: #1d1844; }
.hs-form .hs-form-field:last-child, .hs-form .legal-consent-container { font-size: 16px; color: #5F5C6E; letter-spacing: -0.02em; }
.hs-form-field ul.inputs-list.multi-container { display: flex; flex-direction: row; gap: 1rem; flex-wrap: wrap; list-style: none; padding-left: 0; }
ul.inputs-list.multi-container .hs-form-checkbox-display { display: flex; justify-content: center; align-items: center; }
`;

function HubSpotContactForm({ formId }: { formId: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const formCreated = useRef(false);

  useEffect(() => {
    function tryCreateForm() {
      if (
        formCreated.current ||
        !containerRef.current ||
        typeof window === "undefined" ||
        !(window as any).hbspt
      ) return;

      (window as any).hbspt.forms.create({
        portalId: process.env.NEXT_PUBLIC_HUBSPOT_PORTAL_ID_CONTACT,
        formId,
        target: "#hubspot-form-container",
      });
      formCreated.current = true;

      // Auto-fill email from localStorage (set by the hero form)
      const storedEmail = localStorage.getItem("userEmail");
      if (storedEmail) {
        let attempts = 0;
        const interval = setInterval(() => {
          const form = document.querySelector(`form[data-form-id="${formId}"]`);
          if (form) {
            const emailInput = form.querySelector('input[name="email"]') as HTMLInputElement | null;
            if (emailInput) {
              emailInput.value = storedEmail;
              emailInput.dispatchEvent(new Event("input", { bubbles: true }));
              clearInterval(interval);
            }
          }
          if (++attempts >= 30) clearInterval(interval);
        }, 500);
      }
    }

    // If script already loaded, create immediately
    if ((window as any).hbspt) {
      tryCreateForm();
    }
    // Otherwise the Script onReady will call it
    (window as any).__hubspotFormInit = tryCreateForm;

    return () => {
      (window as any).__hubspotFormInit = undefined;
    };
  }, [formId]);

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: HUBSPOT_FORM_CSS }} />
      <Script
        src="//js-eu1.hsforms.net/forms/embed/v2.js"
        strategy="afterInteractive"
        onReady={() => {
          if ((window as any).__hubspotFormInit) {
            (window as any).__hubspotFormInit();
          }
        }}
      />
      <div id="hubspot-form-container" ref={containerRef} />
    </>
  );
}

export type SectionContactSidebarProps = {
  hubspotFormId?: string;
  subtitle?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * SectionContactSidebar
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function SectionContactSidebar({
  hubspotFormId = "b9355524-ebc4-45f2-bead-b719926b54db",
  subtitle = "Ditto makes it easy to get compliant and stay compliant with frameworks like EcoVadis, ISO, CSRD, and CDP. And that’s just the beginning.",
  title = "Get compliant four times faster",
}: SectionContactSidebarProps) {
  const t = useTranslations("contactSidebar");
  const locale = useLocale();
  const prefix = `/${locale}`;
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={
          "contact_section w-node-_2b3cc0cd-2a32-7e46-40f4-a6f694c26ebc-94c26ebc"
        }
        grid={{
          type: "section",
        }}
        id={"contact"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Small (3rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"contact_component"} tag={"div"}>
              <Block className={"contact_content_wrapper"} tag={"div"}>
                <Block className={"contact_content"} tag={"div"}>
                  <Paragraph className={"heading-size-4rem"}>{title}</Paragraph>
                  <Block className={"spacer-1x5rem"} tag={"div"} />
                  <Paragraph className={"text-size-1x375rem"}>
                    {subtitle}
                  </Paragraph>
                  <Block className={"spacer-3rem"} tag={"div"} />
                  <Heading className={"heading-size-2rem"} tag={"h3"}>
                    {t("companiesUse")}
                  </Heading>
                  <Block className={"spacer-1x5rem"} tag={"div"} />
                  <Block className={"contact_features_list"} tag={"div"}>
                    <Block className={"contact_features_item"} tag={"div"}>
                      <Block className={"contact_features_icon"} tag={"div"}>
                        <HtmlEmbed
                          className={"icon"}
                          content={
                            '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M20.7071 5.29289C21.0976 5.68342 21.0976 6.31658 20.7071 6.70711L9.70711 17.7071C9.31658 18.0976 8.68342 18.0976 8.29289 17.7071L3.29289 12.7071C2.90237 12.3166 2.90237 11.6834 3.29289 11.2929C3.68342 10.9024 4.31658 10.9024 4.70711 11.2929L9 15.5858L19.2929 5.29289C19.6834 4.90237 20.3166 4.90237 20.7071 5.29289Z" fill="#130E30"/>\n</svg>'
                          }
                        />
                      </Block>
                      <Paragraph className={"text-size-1x375rem"}>
                        {t("benefit1")}
                      </Paragraph>
                    </Block>
                    <Block className={"contact_features_item"} tag={"div"}>
                      <Block className={"contact_features_icon"} tag={"div"}>
                        <HtmlEmbed
                          className={"icon"}
                          content={
                            '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M20.7071 5.29289C21.0976 5.68342 21.0976 6.31658 20.7071 6.70711L9.70711 17.7071C9.31658 18.0976 8.68342 18.0976 8.29289 17.7071L3.29289 12.7071C2.90237 12.3166 2.90237 11.6834 3.29289 11.2929C3.68342 10.9024 4.31658 10.9024 4.70711 11.2929L9 15.5858L19.2929 5.29289C19.6834 4.90237 20.3166 4.90237 20.7071 5.29289Z" fill="#130E30"/>\n</svg>'
                          }
                        />
                      </Block>
                      <Paragraph className={"text-size-1x375rem"}>
                        {t("benefit2")}
                      </Paragraph>
                    </Block>
                    <Block className={"contact_features_item"} tag={"div"}>
                      <Block className={"contact_features_icon"} tag={"div"}>
                        <HtmlEmbed
                          className={"icon"}
                          content={
                            '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M20.7071 5.29289C21.0976 5.68342 21.0976 6.31658 20.7071 6.70711L9.70711 17.7071C9.31658 18.0976 8.68342 18.0976 8.29289 17.7071L3.29289 12.7071C2.90237 12.3166 2.90237 11.6834 3.29289 11.2929C3.68342 10.9024 4.31658 10.9024 4.70711 11.2929L9 15.5858L19.2929 5.29289C19.6834 4.90237 20.3166 4.90237 20.7071 5.29289Z" fill="#130E30"/>\n</svg>'
                          }
                        />
                      </Block>
                      <Paragraph className={"text-size-1x375rem"}>
                        {t("benefit3")}
                      </Paragraph>
                    </Block>
                    <Block className={"contact_features_item"} tag={"div"}>
                      <Block className={"contact_features_icon"} tag={"div"}>
                        <HtmlEmbed
                          className={"icon"}
                          content={
                            '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M20.7071 5.29289C21.0976 5.68342 21.0976 6.31658 20.7071 6.70711L9.70711 17.7071C9.31658 18.0976 8.68342 18.0976 8.29289 17.7071L3.29289 12.7071C2.90237 12.3166 2.90237 11.6834 3.29289 11.2929C3.68342 10.9024 4.31658 10.9024 4.70711 11.2929L9 15.5858L19.2929 5.29289C19.6834 4.90237 20.3166 4.90237 20.7071 5.29289Z" fill="#130E30"/>\n</svg>'
                          }
                        />
                      </Block>
                      <Paragraph className={"text-size-1x375rem"}>
                        {t("benefit4")}
                      </Paragraph>
                    </Block>
                  </Block>
                </Block>
              </Block>
              <Block className={"contact_form_wrapper"} tag={"div"}>
                <Block className={"contact_form"} tag={"div"}>
                  <HubSpotContactForm formId={hubspotFormId} />
                </Block>
              </Block>
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
