/**
 * @generated
 * @file BlogUiList (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import FormErrorMessage from "../webflow_modules/Form/components/FormErrorMessage";
import FormForm from "../webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "../webflow_modules/Form/components/FormSuccessMessage";
import FormTextInput from "../webflow_modules/Form/components/FormTextInput";
import FormWrapper from "../webflow_modules/Form/components/FormWrapper";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link BlogUiList}
 */
export type BlogUiListProps = {
  displaySearchbar?: boolean;
};

/**
 * BlogUiList
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function BlogUiList({ displaySearchbar = true }: BlogUiListProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"blogui_block"} tag={"div"}>
        <Block className={"blogui_list"} tag={"div"}>
          <Link
            block={""}
            button={false}
            className={"blogui_link"}
            options={{
              href: "/en/resources",
            }}
          >
            {"All"}
          </Link>
          <Link
            block={""}
            button={false}
            className={"blogui_link"}
            options={{
              href: "/en/resources/blog",
            }}
          >
            {"Blog"}
          </Link>
          <Link
            block={""}
            button={false}
            className={"blogui_link"}
            options={{
              href: "/en/resources/news",
            }}
          >
            {"News"}
          </Link>
          <Link
            block={""}
            button={false}
            className={"blogui_link"}
            options={{
              href: "/en/resources/guides",
            }}
          >
            {"Guide"}
          </Link>
        </Block>
        {displaySearchbar ? (
          <FormWrapper className={"blogui_search_block"}>
            <FormForm
              className={"blogui_search_form"}
              data-name={"open-search"}
              fs-list-element={"filters"}
              id={"wf-form-open-search"}
              method={"get"}
              name={"wf-form-open-search"}
            >
              <Block className={"blogui_search_search_wrapper"} tag={"div"}>
                <Block className={"blogui_search_icon"} tag={"div"}>
                  <HtmlEmbed
                    className={"icon"}
                    content={
                      '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M11 2C15.9706 2 20 6.02944 20 11C20 13.125 19.2619 15.0766 18.0303 16.6162L21.707 20.293L21.7764 20.3691C22.0963 20.7619 22.0729 21.3411 21.707 21.707C21.3411 22.073 20.7619 22.0963 20.3691 21.7764L20.293 21.707L16.6162 18.0303C15.0766 19.2619 13.125 20 11 20C6.02944 20 2 15.9706 2 11C2 6.02944 6.02944 2 11 2ZM11 4C7.13401 4 4 7.13401 4 11C4 14.866 7.13401 18 11 18C14.866 18 18 14.866 18 11C18 7.13401 14.866 4 11 4Z" fill="#130E30"/>\n</svg>'
                    }
                  />
                </Block>
                <FormTextInput
                  autoFocus={false}
                  className={"blogui_search_input_wrapper"}
                  data-name={"Field 3"}
                  disabled={false}
                  fs-list-field={"*"}
                  id={"field-3"}
                  maxLength={256}
                  name={"field-3"}
                  placeholder={"Search"}
                  required={true}
                  type={"text"}
                />
                <Block className={"blogui_search_close"} tag={"div"}>
                  <HtmlEmbed
                    className={"icon"}
                    content={
                      '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M18 6L6 18" stroke="#130E30" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M6 6L18 18" stroke="#130E30" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>'
                    }
                  />
                </Block>
                <DOM
                  aria-label={"togle search input visibility"}
                  className={"blogui_search_checkbox"}
                  tag={"input"}
                  type={"checkbox"}
                />
              </Block>
            </FormForm>
            <FormSuccessMessage>
              <Block tag={"div"}>
                {"Thank you! Your submission has been received!"}
              </Block>
            </FormSuccessMessage>
            <FormErrorMessage>
              <Block tag={"div"}>
                {"Oops! Something went wrong while submitting the form."}
              </Block>
            </FormErrorMessage>
          </FormWrapper>
        ) : null}
      </Block>
    </div>
  );
}
