/**
 * @generated
 * @file ButtonTiny (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link ButtonTiny}
 */
export type ButtonTinyProps = {
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
};

/**
 * ButtonTiny
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function ButtonTiny({
  link = {
    href: "#",
  },

  text = "Button Text",
}: ButtonTinyProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"button_tiny"}
        options={link}
      >
        <Block tag={"div"}>{text}</Block>
        <Block className={"icon-wrapper"} tag={"div"}>
          <HtmlEmbed
            className={"icon"}
            content={
              '<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M4.14645 2.64645C4.34171 2.45118 4.65829 2.45118 4.85355 2.64645L7.85355 5.64645C8.04882 5.84171 8.04882 6.15829 7.85355 6.35355L4.85355 9.35355C4.65829 9.54882 4.34171 9.54882 4.14645 9.35355C3.95118 9.15829 3.95118 8.84171 4.14645 8.64645L6.79289 6L4.14645 3.35355C3.95118 3.15829 3.95118 2.84171 4.14645 2.64645Z" fill="currentColor"/>\n</svg>'
            }
          />
        </Block>
      </Link>
    </div>
  );
}
