/**
 * @generated
 * @file Button (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link Button}
 */
export type ButtonProps = {
  ariaLabel?: string;
  arrow?: boolean;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  rel?: string;
  text?: React.ReactNode;
  variant?: "Primary" | "Secondary" | "Tertiary" | "Primary - Small";
};

/**
 * Button
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function Button({
  ariaLabel = "",
  arrow = true,

  link = {
    href: "/en/get-started",
  },

  rel = "",
  text = "Button Text",
  variant = "Primary",
}: ButtonProps) {
  const _styleVariantMap = {
    Primary: "",
    Secondary: "w-variant-65493725-7ae1-e50b-73f7-cdb2cb7a8365",
    Tertiary: "w-variant-c572cae4-b61f-2981-ba94-f7cf19f911a8",
    "Primary - Small": "w-variant-a49ac11c-dff4-0c97-be6d-a3422e4bdf24",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        aria-label={ariaLabel}
        block={"inline"}
        button={false}
        className={`button ${_activeStyleVariant}`}
        options={link}
        // @ts-ignore - User-defined custom attribute(s)
        rel={rel}
      >
        <Block tag={"div"}>{text}</Block>
        {arrow ? (
          <Block className={`icon-wrapper ${_activeStyleVariant}`} tag={"div"}>
            <HtmlEmbed
              className={`icon ${_activeStyleVariant}`}
              content={
                '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M3.52876 5.52851C3.78911 5.26816 4.21122 5.26816 4.47157 5.52851L8.00016 9.05711L11.5288 5.52851C11.7891 5.26816 12.2112 5.26816 12.4716 5.52851C12.7319 5.78886 12.7319 6.21097 12.4716 6.47132L8.47157 10.4713C8.21122 10.7317 7.78911 10.7317 7.52876 10.4713L3.52876 6.47132C3.26841 6.21097 3.26841 5.78886 3.52876 5.52851Z" fill="currentColor"/>\n</svg>'
              }
            />
          </Block>
        ) : null}
      </Link>
    </div>
  );
}
