/**
 * @generated
 * @file ElementCareersItem (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link ElementCareersItem}
 */
export type ElementCareersItemProps = {
  jobTitle?: React.ReactNode;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  office?: React.ReactNode;
  time?: React.ReactNode;
  type?: React.ReactNode;
};

/**
 * ElementCareersItem
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function ElementCareersItem({
  jobTitle = "AI Workflow Engineer",

  link = {
    href: "#",
  },

  office = "Paris Office",
  time = "Fulltime",
  type = "Engineering & Data",
}: ElementCareersItemProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"careers-list_item"} tag={"div"}>
        <Block className={"careers-list_content"} tag={"div"}>
          <Link
            block={""}
            button={false}
            className={"text-size-1x375rem link-hover-parent"}
            options={link}
          >
            {jobTitle}
          </Link>
          <Block className={"spacer-0x5rem"} tag={"div"} />
          <DOM className={"text-size-1rem"} tag={"p"}>
            <DOM tag={"span"}>{type}</DOM>
            <DOM tag={"span"}>{"• "}</DOM>
            <DOM tag={"span"}>{office}</DOM>
            <DOM tag={"span"}>{"• "}</DOM>
            <DOM tag={"span"}>{time}</DOM>
          </DOM>
        </Block>
        <Block className={"careers-list_card"} tag={"div"}>
          <HtmlEmbed
            className={"icon"}
            content={
              '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M5 12H19" stroke="#130E30" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M12 5L19 12L12 19" stroke="#130E30" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>'
            }
          />
        </Block>
      </Block>
    </div>
  );
}
