/**
 * @generated
 * @file ElementSocialproofTrustpilot (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import DOM from "../webflow_modules/Builtin/components/DOM";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link ElementSocialproofTrustpilot}
 */
export type ElementSocialproofTrustpilotProps = {
  image?: string;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text1?: React.ReactNode;
  text2?: React.ReactNode;
};

/**
 * ElementSocialproofTrustpilot
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function ElementSocialproofTrustpilot({
  image = "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/69a7fb7319962df0c9f5adbc_trustpilot-2.svg",

  link = {
    href: "https://fr.trustpilot.com/review/trustditto.com",
    target: "_blank",
  },

  text1 = "4.6",
  text2 = "on Trustpilot",
}: ElementSocialproofTrustpilotProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"socialproof_item"} tag={"div"}>
        <Link
          block={"inline"}
          button={false}
          className={"text-size-1x125rem"}
          options={{
            href: "https://fr.trustpilot.com/review/trustditto.com",
            target: "_blank",
          }}
        >
          <DOM className={"text-weight-600"} tag={"span"}>
            {text1}
          </DOM>
          <DOM className={"text-color-neutral"} tag={"span"}>
            {"/5"}
          </DOM>
          <DOM className={"text-color-neutral"} tag={"span"}>
            {text2}
          </DOM>
        </Link>
        <Image
          alt={""}
          height={"auto"}
          loading={"lazy"}
          src={image}
          width={"28"}
        />
      </Block>
    </div>
  );
}
