/**
 * @generated
 * @file Label (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link Label}
 */
export type LabelProps = {
  label?: React.ReactNode;
};

/**
 * Label
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function Label({ label = "lorem ipsum" }: LabelProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Paragraph className={"label"}>{label}</Paragraph>
    </div>
  );
}
