/**
 * @generated
 * @file SectionResources (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Image from "../modules/Basic/components/Image";
import Link from "../modules/Basic/components/Link";
import NotSupported from "../modules/Builtin/components/NotSupported";
import Paragraph from "../modules/Basic/components/Paragraph";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { Button } from "../elements/Button";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionResources}
 */
export type SectionResourcesProps = {
  title?: React.ReactNode;
};

/**
 * SectionResources
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 */
export function SectionResources({
  title = "Learn more about Ditto & AI-powered CSR compliance",
}: SectionResourcesProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"blog-preview_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-f5af8294-c768-4701-7754-9613b683c062-b683c062"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Small (3rem)"} />
          <Block className={"container-48rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {title}
              </Heading>
            </Block>
          </Block>
          <Block className={"spacer-3rem"} tag={"div"} />
          <Block className={"container-80rem"} tag={"div"}>
            <NotSupported _atom={"Collection List"} />
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block className={"button-group x-center"} tag={"div"}>
              <Button
                arrow={false}
                link={{
                  href: "/en/resources",
                }}
                text={"View All Resources"}
                variant={"Secondary"}
              />
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
