/**
 * @generated
 * @file SectionLogostrip (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";
import Image from "../modules/Basic/components/Image";
import Link from "../modules/Basic/components/Link";
import NotSupported from "../modules/Builtin/components/NotSupported";
import Paragraph from "../modules/Basic/components/Paragraph";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionLogostrip}
 */
export type SectionLogostripProps = {
  variant?: "Base" | "Not clickable";
};

/**
 * SectionLogostrip
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 */
export function SectionLogostrip({ variant = "Base" }: SectionLogostripProps) {
  const _styleVariantMap = {
    Base: "",
    "Not clickable": "w-variant-4264a7db-e569-0907-b261-b783f2c8be66",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`logostrip_section ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        id={"w-node-fe04e33d-a26d-fee6-d70d-7145bfe0c248-bfe0c248"}
        tag={"section"}
      >
        <Block className={`padding-global ${_activeStyleVariant}`} tag={"div"}>
          <Padding space={"Small (3rem)"} />
          <Block
            className={`container-80rem ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block className={`header ${_activeStyleVariant}`} tag={"div"}>
              <Heading
                className={`text-size-1rem text-weight-400 ${_activeStyleVariant}`}
                tag={"h2"}
              >
                {"Join 500+ companies managing their compliance with Ditto"}
              </Heading>
            </Block>
            <Block
              className={`spacer-2rem ${_activeStyleVariant}`}
              tag={"div"}
            />
            <NotSupported _atom={"Collection List"} />
          </Block>
          <Padding space={"Small (3rem)"} />
        </Block>
        <Block className={`layer-4 ${_activeStyleVariant}`} tag={"div"}>
          <Background color={"Secondary"} />
        </Block>
      </Section>
    </div>
  );
}
