/**
 * @generated
 * @file SectionBreadcrumbs (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";
import Link from "../modules/Basic/components/Link";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";

/**
 * Props for {@link SectionBreadcrumbs}
 */
export type SectionBreadcrumbsProps = {
  backgroundBackground?:
    | "Primary"
    | "Secondary"
    | "Tertiary"
    | "Transparent"
    | "Yellow";
  item1Item1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  item1Item1Text?: React.ReactNode;
  item2Item2Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  item2Item2Text?: React.ReactNode;
  item2Item2Visibility?: boolean;
  item3Item3Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  item3Item3Text?: React.ReactNode;
  item3Item3Visibility?: boolean;
};

/**
 * SectionBreadcrumbs
 *
 */
export function SectionBreadcrumbs({
  backgroundBackground = "Primary",

  item1Item1Link = {
    href: "#",
  },

  item1Item1Text = "Lorem ipsum",

  item2Item2Link = {
    href: "#",
  },

  item2Item2Text = "Lorem ipsum",
  item2Item2Visibility = true,

  item3Item3Link = {
    href: "#",
  },

  item3Item3Text = "Lorem ipsum",
  item3Item3Visibility = false,
}: SectionBreadcrumbsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"breadcrumbs_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_82f23438-124f-349a-e1c4-69e0ddbaab7f-ddbaab7f"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Block className={"spacer-1x5rem"} tag={"div"} />
          <Block className={"container-80rem"} tag={"div"}>
            <Block className={"breadcrumbs_list"} tag={"div"}>
              <Link
                block={""}
                button={false}
                className={"link-size-1rem"}
                options={item1Item1Link}
              >
                {item1Item1Text}
              </Link>
              {item2Item2Visibility ? (
                <Block className={"icon-wrapper"} tag={"div"}>
                  <HtmlEmbed
                    className={"icon"}
                    content={
                      '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M5.5312 3.52729C5.79155 3.26694 6.21366 3.26694 6.47401 3.52729L10.474 7.52729C10.7344 7.78764 10.7344 8.20975 10.474 8.4701L6.47401 12.4701C6.21366 12.7305 5.79155 12.7305 5.5312 12.4701C5.27085 12.2098 5.27085 11.7876 5.5312 11.5273L9.0598 7.9987L5.5312 4.4701C5.27085 4.20975 5.27085 3.78764 5.5312 3.52729Z" fill="#5F5C6E"/>\n</svg>'
                    }
                  />
                </Block>
              ) : null}
              {item2Item2Visibility ? (
                <Link
                  block={""}
                  button={false}
                  className={"link-size-1rem"}
                  options={item2Item2Link}
                >
                  {item2Item2Text}
                </Link>
              ) : null}
              {item3Item3Visibility ? (
                <Block className={"icon-wrapper"} tag={"div"}>
                  <HtmlEmbed
                    className={"icon"}
                    content={
                      '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M5.5312 3.52729C5.79155 3.26694 6.21366 3.26694 6.47401 3.52729L10.474 7.52729C10.7344 7.78764 10.7344 8.20975 10.474 8.4701L6.47401 12.4701C6.21366 12.7305 5.79155 12.7305 5.5312 12.4701C5.27085 12.2098 5.27085 11.7876 5.5312 11.5273L9.0598 7.9987L5.5312 4.4701C5.27085 4.20975 5.27085 3.78764 5.5312 3.52729Z" fill="#5F5C6E"/>\n</svg>'
                    }
                  />
                </Block>
              ) : null}
              {item3Item3Visibility ? (
                <Link
                  block={""}
                  button={false}
                  className={"link-size-1rem"}
                  options={item3Item3Link}
                >
                  {item3Item3Text}
                </Link>
              ) : null}
            </Block>
          </Block>
          <Block className={"spacer-1x5rem"} tag={"div"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={backgroundBackground} />
        </Block>
      </Section>
    </div>
  );
}
