/**
 * @generated
 * @file SectionCollectionEcovadis (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Image from "../modules/Basic/components/Image";
import NotSupported from "../modules/Builtin/components/NotSupported";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { ElementCollectionArticleLink } from "../elements/ElementCollectionArticleLink";
import { Label } from "../elements/Label";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionCollectionEcovadis}
 */
export type SectionCollectionEcovadisProps = {
  background?: "Primary" | "Secondary" | "Tertiary" | "Transparent" | "Yellow";
};

/**
 * SectionCollectionEcovadis
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 */
export function SectionCollectionEcovadis({
  background = "Tertiary",
}: SectionCollectionEcovadisProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"collection_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_262ae919-6d70-01bc-b48f-92a15f24deeb-5f24deeb"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-70rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Label label={"Articles"} />
              <Block className={"spacer-1x5rem"} tag={"div"} />
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {"Explore EcoVadis articles"}
              </Heading>
            </Block>
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block className={"collection_component"} tag={"div"}>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c1520f8ba57b7a6b29c2_Icon-4.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Introduction to EcoVadis"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c152c34ca7caf3a490b8_Icon-1.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Preparing for a EcoVadis audit"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c152cad37b73c312337f_Icon-12.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Succeeding with EcoVadis"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c152cf1d54d25b2a5ff2_Icon-2.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"EcoVadis performance & results"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c152405312512f5d8b66_Icon-5.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"EcoVadis compared to other frameworks"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c1528594922b61752e25_Icon-6.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"EcoVadis by company size and industry"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6887c1520f8ba57b7a6b29c2_Icon-4.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Additional EcoVadis resources"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={background} />
        </Block>
      </Section>
    </div>
  );
}
