/**
 * @generated
 * @file SectionTestimonials (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import NotSupported from "../modules/Builtin/components/NotSupported";
import Paragraph from "../modules/Basic/components/Paragraph";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { Button } from "../elements/Button";
import { CardTestimonial } from "../elements/CardTestimonial";
import { CarouselButtonNext } from "../elements/CarouselButtonNext";
import { CarouselButtonPrevious } from "../elements/CarouselButtonPrevious";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionTestimonials}
 */
export type SectionTestimonialsProps = {
  buttonLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonText?: React.ReactNode;
  text?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * SectionTestimonials
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 */
export function SectionTestimonials({
  buttonLink = {
    href: "/en/customer-stories",
  },

  buttonText = "Read More",
  text = "Customers of all sizes love Ditto for its simplicity, smarts, and impact, above all.",
  title = "What teams are saying",
}: SectionTestimonialsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"carousel_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_3bc96074-d8ef-94b2-8c5e-1514982ed182-982ed182"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-48rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {title}
              </Heading>
              <Block className={"spacer-1x5rem"} tag={"div"} />
              <Paragraph className={"text-size-1x375rem text-wrap-balance"}>
                {text}
              </Paragraph>
              <Block className={"spacer-1x5rem"} tag={"div"} />
              <Block tag={"div"}>
                <Button
                  arrow={false}
                  link={buttonLink}
                  text={buttonText}
                  variant={"Secondary"}
                />
              </Block>
            </Block>
          </Block>
          <Block className={"spacer-3rem"} tag={"div"} />
          <Block className={"container-80rem"} tag={"div"}>
            <Block
              className={"carousel_component"}
              // @ts-ignore - User-defined custom attribute(s)
              splide={"carousel"}
              splide-direction={"ltr"}
              splide-gap={"3rem"}
              splide-gap-mobile={"1rem"}
              splide-interval={"5000"}
              tag={"div"}
            >
              <Block className={"carousel_splide_wrapper"} tag={"div"}>
                <Block className={"carousel_splide splide"} tag={"div"}>
                  <NotSupported _atom={"Collection List"} />
                </Block>
                <Block className={"carousel_navigation_wrapper"} tag={"div"}>
                  <CarouselButtonPrevious />
                  <CarouselButtonNext />
                </Block>
              </Block>
              <Block className={"spacer-1x5rem"} tag={"div"} />
              <Block className={"carousel_pagination_list"} tag={"div"}>
                <Block
                  className={"carousel_pagination_button"}
                  splide-button={"pagination"}
                  tag={"div"}
                />
                <Block
                  className={"carousel_pagination_button is-active"}
                  tag={"div"}
                />
              </Block>
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Tertiary"} />
        </Block>
      </Section>
    </div>
  );
}
