/**
 * @generated
 * @file SectionInvestors (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Image from "../modules/Basic/components/Image";
import Paragraph from "../modules/Basic/components/Paragraph";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionInvestors}
 */
export type SectionInvestorsProps = {};

/**
 * SectionInvestors
 *
 */
export function SectionInvestors({}: SectionInvestorsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"investors_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_33a8a2c6-1672-e7c8-aad4-d9fb9bc86e9e-9bc86e9e"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Small (3rem)"} />
          <Block className={"container-84rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {"Our investors"}
              </Heading>
              <Block className={"spacer-0x75rem"} tag={"div"} />
              <Paragraph className={"text-size-1rem"}>
                {
                  "Partnership is in our DNA and we’re proud to work with many of the best."
                }
              </Paragraph>
              <Block className={"spacer-2rem"} tag={"div"} />
              <Block className={"investors_list"} tag={"div"}>
                <Image
                  alt={""}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6835b96085a32e7106c24bfb_nine.avif"
                  }
                  width={"59"}
                />
                <Image
                  alt={""}
                  className={"mix-blend-mode-multiply"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6835b9606ef3fedec0757bf1_purple.avif"
                  }
                  width={"70"}
                />
                <Image
                  alt={""}
                  className={"mix-blend-mode-multiply"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6835b960ce58e09d2418ad5e_better-angle.avif"
                  }
                  width={"78"}
                />
                <Image
                  alt={""}
                  className={"mix-blend-mode-multiply"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6835b96042c32bcf5e05cab4_aonia.avif"
                  }
                  width={"80"}
                />
                <Image
                  alt={""}
                  className={"mix-blend-mode-multiply"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6835b960f81118f10549ee7a_kima-ventures.avif"
                  }
                  width={"80"}
                />
                <Image
                  alt={""}
                  className={"mix-blend-mode-multiply"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/6835b960ce3117638f74790e_motier-ventures.avif"
                  }
                  width={"120"}
                />
              </Block>
            </Block>
          </Block>
          <Padding space={"Small (3rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Secondary"} />
        </Block>
      </Section>
    </div>
  );
}
