/**
 * @generated
 * @file SectionPillIllus (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import HtmlEmbed from "../modules/Embed/components/HtmlEmbed";
import Image from "../modules/Basic/components/Image";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionPillIllus}
 */
export type SectionPillIllusProps = {
  image?: string;
};

/**
 * SectionPillIllus
 *
 */
export function SectionPillIllus({
  image = "https://xrbgrzbifkchbjimewvu.supabase.co/storage/v1/object/public/cms-images/static/682ee40e21f304d2370b1de0_happy-business-meeting-team-laughing.avif",
}: SectionPillIllusProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"pill-illus_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-aab1d619-0ebd-162b-4b97-15e90cbbfc5c-0cbbfc5c"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Large (9rem)"} />
          <Block className={"pill-illus_wrapper"} tag={"div"}>
            <Image
              alt={""}
              className={"media-full-size"}
              height={"auto"}
              loading={"lazy"}
              src={image}
              width={"auto"}
            />
          </Block>
          <Block className={"pill-illus_cutouts_wrapper"} tag={"div"}>
            <HtmlEmbed
              className={"pill-illus_cutouts_embed hide-tablet"}
              content={
                '<svg width="100%" height="100%" viewBox="0 0 1544 202" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<rect width="274.974" height="186.972" rx="93.486" transform="matrix(-1 0 0 1 412.688 7.05469)" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="126.064" height="186.972" rx="63.032" transform="matrix(-1 0 0 1 166.016 7.05469)" fill="#E261E5"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="79.8956" height="201.322" rx="39.9478" fill="#FFE228"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="160.047" height="186.972" rx="80.0234" transform="matrix(-1 0 0 1 1543.75 7.05469)" fill="#E261E5"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="1332.99" width="101.433" height="201.322" rx="50.7165" fill="#FFE228"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="1207" y="27.7734" width="141.404" height="145.775" rx="70.702" fill="#59E25D"/>\n</g>\n</svg>'
              }
            />
            <HtmlEmbed
              className={"pill-illus_cutouts_embed show-tablet"}
              content={
                '<svg width="664" height="160" viewBox="0 0 664 160" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g style="mix-blend-mode:multiply">\n<rect width="218.535" height="148.595" rx="74.2976" transform="matrix(-1 0 0 1 327.977 5.60547)" fill="#3A93FF"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="100.189" height="148.595" rx="50.0944" transform="matrix(-1 0 0 1 131.938 5.60938)" fill="#E261E5"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="63.4968" height="160" rx="31.7484" fill="#FFE228"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect width="127.197" height="148.595" rx="63.5983" transform="matrix(-1 0 0 1 663.633 5.60938)" fill="#E261E5"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="496.133" width="80.6134" height="160" rx="40.3067" fill="#FFE228"/>\n</g>\n<g style="mix-blend-mode:multiply">\n<rect x="396" y="22.0703" width="112.38" height="115.854" rx="56.1901" fill="#59E25D"/>\n</g>\n</svg>'
              }
            />
          </Block>
          <Padding space={"None"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
