/**
 * @generated
 * @file SectionCollectionCdp (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Image from "../modules/Basic/components/Image";
import NotSupported from "../modules/Builtin/components/NotSupported";
import Section from "../modules/Layout/components/Section";
import { Background } from "../Background";
import { ElementCollectionArticleLink } from "../elements/ElementCollectionArticleLink";
import { Label } from "../elements/Label";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionCollectionCdp}
 */
export type SectionCollectionCdpProps = {};

/**
 * SectionCollectionCdp
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 */
export function SectionCollectionCdp({}: SectionCollectionCdpProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"collection_section"}
        grid={{
          type: "section",
        }}
        id={"w-node-_92bc3383-735f-e755-ca9a-844b83af220a-83af220a"}
        tag={"section"}
      >
        <Block className={"padding-global"} tag={"div"}>
          <Padding space={"Medium (6rem)"} />
          <Block className={"container-70rem"} tag={"div"}>
            <Block className={"header"} tag={"div"}>
              <Label label={"Articles"} />
              <Block className={"spacer-1x5rem"} tag={"div"} />
              <Heading className={"heading-size-3rem"} tag={"h2"}>
                {"Explore CDP articles"}
              </Heading>
            </Block>
            <Block className={"spacer-3rem"} tag={"div"} />
            <Block className={"collection_component"} tag={"div"}>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c1520f8ba57b7a6b29c2_Icon%204.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Introduction to CDP"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c152c34ca7caf3a490b8_Icon%201.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Preparing for a CDP audit"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c152cad37b73c312337f_Icon%2012.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Succeeding with CDP"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c152cf1d54d25b2a5ff2_Icon%202.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"CDP performance & results"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c152405312512f5d8b66_Icon%205.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"CDP compared to other frameworks"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <Block
                  className={"collection_list margin-bottom-0x75rem"}
                  tag={"div"}
                >
                  <ElementCollectionArticleLink
                    link={{
                      href: "/en/collection/ecovadis/ecovadis-vs-cdp",
                    }}
                    text={"EcoVadis vs CDP"}
                  />
                </Block>
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c1528594922b61752e25_Icon%206.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"CDP by company size and industry"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block className={"collection_col"} tag={"div"}>
                <Block className={"collection_col_header"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={
                      "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/6887c1520f8ba57b7a6b29c2_Icon%204.png"
                    }
                    width={"40"}
                  />
                  <Heading className={"heading-size-1x75rem"} tag={"h3"}>
                    {"Additional CDP resources"}
                  </Heading>
                </Block>
                <Block className={"spacer-1x5rem"} tag={"div"} />
                <NotSupported _atom={"Collection List"} />
                <NotSupported _atom={"Collection List"} />
              </Block>
            </Block>
          </Block>
          <Padding space={"Medium (6rem)"} />
        </Block>
        <Block className={"layer-4"} tag={"div"}>
          <Background color={"Tertiary"} />
        </Block>
      </Section>
    </div>
  );
}
