/**
 * @generated
 * @file SectionCompliantCarousel (generated by DevLink)
 *
 * This file is generated by DevLink. Manual edits are discouraged.
 *
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../modules/Basic/components/Block";
import Heading from "../modules/Basic/components/Heading";
import Section from "../modules/Layout/components/Section";
import Strong from "../modules/Basic/components/Strong";
import { Background } from "../Background";
import { CardIcon } from "../elements/CardIcon";
import { Padding } from "../Padding";

/**
 * Props for {@link SectionCompliantCarousel}
 */
export type SectionCompliantCarouselProps = {
  spaceBottom?: "Small (3rem)" | "Medium (6rem)" | "Large (9rem)" | "None";
  spaceTop?: "Small (3rem)" | "Medium (6rem)" | "Large (9rem)" | "None";
  title?: React.ReactNode;
  variant?: "Base" | "Title larger";
};

/**
 * SectionCompliantCarousel
 *
 */
export function SectionCompliantCarousel({
  spaceBottom = "None",
  spaceTop = "Medium (6rem)",
  title = "Lorem ipsum",
  variant = "Base",
}: SectionCompliantCarouselProps) {
  const _styleVariantMap = {
    Base: "",
    "Title larger": "w-variant-206a19d0-2893-3fb0-f589-5ad4d034675d",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`carousel_section ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        id={"w-node-dbe1ed5b-a393-8703-f7a4-d71109b8c788-09b8c788"}
        tag={"section"}
      >
        <Block className={`padding-global ${_activeStyleVariant}`} tag={"div"}>
          <Padding space={spaceTop} />
          <Block
            className={`container-84rem ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`max-width-32rem ${_activeStyleVariant}`}
              tag={"div"}
            />
            <Heading
              className={`heading-size-3rem text-wrap-balance ${_activeStyleVariant}`}
              tag={"h2"}
            >
              {title}
            </Heading>
            <Block
              className={`spacer-3rem ${_activeStyleVariant}`}
              tag={"div"}
            />
            <Block
              className={`carousel_component ${_activeStyleVariant}`}
              // @ts-ignore - User-defined custom attribute(s)
              splide={"carousel"}
              splide-direction={"ltr"}
              splide-gap={"3rem"}
              splide-gap-mobile={"1rem"}
              splide-interval={"5000"}
              tag={"div"}
            >
              <Block
                className={`carousel_splide_wrapper ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`carousel_splide splide width-26rem ${_activeStyleVariant}`}
                  tag={"div"}
                >
                  <Block
                    className={`carousel_track splide__track ${_activeStyleVariant}`}
                    tag={"div"}
                  >
                    <Block
                      className={`carousel_list splide__list designer ${_activeStyleVariant}`}
                      tag={"div"}
                    >
                      <Block
                        className={`carousel_slide splide__slide width-26rem ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <CardIcon
                          description={
                            "Comply with CSRD requirements and prepare your sustainability report directly in Ditto"
                          }
                          icon={
                            "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682ed169cfc14d8e3135faa6_Csrd.avif"
                          }
                          title={<Strong>{"CSRD"}</Strong>}
                        />
                      </Block>
                      <Block
                        className={`carousel_slide splide__slide ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <CardIcon
                          description={
                            "Structure your approach, prepare for the EcoVadis assessment, and earn the medal you deserve"
                          }
                          icon={
                            "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682ed1c26a35724770ef7a90_Ecovadis.avif"
                          }
                          title={"EcoVadis"}
                        />
                      </Block>
                      <Block
                        className={`carousel_slide splide__slide ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <CardIcon
                          description={
                            "Organize all of your audit info and prepare your ISO certifications for 14001, 45001, and 50001"
                          }
                          icon={
                            "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682ed1c27d430a77816d3240_Iso.avif"
                          }
                          title={"ISO"}
                        />
                      </Block>
                      <Block
                        className={`carousel_slide splide__slide ${_activeStyleVariant}`}
                        tag={"div"}
                      >
                        <CardIcon
                          description={
                            "Get your best score by takingadvantage of Ditto's structure and expertise for the CDP evaluation"
                          }
                          icon={
                            "https://cdn.prod.website-files.com/682d7fad3c89203197a56faa/682ed1c2ab419262c58ece95_Cdp.avif"
                          }
                          title={"CDP"}
                        />
                      </Block>
                    </Block>
                  </Block>
                </Block>
                <Block
                  className={`carousel_navigation_wrapper ${_activeStyleVariant}`}
                  tag={"div"}
                />
              </Block>
              <Block
                className={`spacer-1x5rem ${_activeStyleVariant}`}
                tag={"div"}
              />
              <Block
                className={`carousel_pagination_list ${_activeStyleVariant}`}
                tag={"div"}
              >
                <Block
                  className={`carousel_pagination_button ${_activeStyleVariant}`}
                  splide-button={"pagination"}
                  tag={"div"}
                />
                <Block
                  className={`carousel_pagination_button is-active ${_activeStyleVariant}`}
                  tag={"div"}
                />
              </Block>
            </Block>
          </Block>
          <Padding space={spaceBottom} />
        </Block>
        <Block className={`layer-4 ${_activeStyleVariant}`} tag={"div"}>
          <Background color={"Primary"} />
        </Block>
      </Section>
    </div>
  );
}
