/**
 * @generated
 * @file Background (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";

/**
 * Props for {@link Background}
 */
export type BackgroundProps = {
  color?: "Primary" | "Secondary" | "Tertiary" | "Transparent" | "Yellow";
};

/**
 * Background
 *
 * @see {@link https://ditto-preprod.design.webflow.com | Source site in Webflow}
 */
export function Background({ color = "Primary" }: BackgroundProps) {
  const _styleVariantMap = {
    Primary: "",
    Secondary: "w-variant-d4e67767-ab3f-6e5c-2116-e9a6d2688920",
    Tertiary: "w-variant-11920b65-344f-1da9-05e0-96a7f0f1de3a",
    Transparent: "w-variant-2407d896-e89c-bb5b-9586-8732f368dcc6",
    Yellow: "w-variant-a7dfcbb5-832b-e2f7-5007-3979e521cf50",
  };

  const _activeStyleVariant = _styleVariantMap[color];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={`background ${_activeStyleVariant}`} tag={"div"} />
    </div>
  );
}
